### ISSUE TITLE
[Feature Request] add "clear console" button to console menu

### ISSUE THREAD

**Issue by teonbrooks** [iodide-project/iodide#1015]
Was testing some things on extremely-alpha and I noticed a feature that would be nice to have: an ability to clear the console. I don't know if there are system level commands in iodide, but a `clear` command would be great.

**Comment by hamilton** [comment]
big +1 to this idea. I'll assign it to myself. Expect a fix early next week.

**Comment by teonbrooks** [comment]
yay, thanks @hamilton! 🎉

**Comment by imranariffin** [comment]
After dicussion with @wlach during Pycon 2019 Sprint it appears this issue was already worked on and merged by PR #1119 but later reverted, the labels "help wanted" and "good first issue" should probably be removed.

**Comment by bcolloran** [comment]
@imranariffin thanks for the comment! i think this probably is a still a good first issue, as the scope has changed since the original implementation about a year ago -- there is now a menu component in the console, and this issue would just require the addition of a entry in that menu that clears the evaluation history in the redux store, which should be pretty simple. It would just be:

```
languages (js, python, etc)
-------(divder)
clear evaluation history
```

the hardest part will probably be figuring out the right way to add divider to the menu...

cc @wlach

**Comment by wlach** [comment]
@bcolloran makes sense to me! @imranariffin -- let me know if you're interested in working on this afterwards.

**Comment by imranariffin** [comment]
If @wlach I'm really happy to pick up this one afterwards, but first let's see how well I do on my current issue #2445 xD
