### ISSUE TITLE
Using keyboard shortcuts for each available language may not scale

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#1065]
With the new "seamless" language loading, "known" languages show up on the cell menu and as a keyboard shortcut, even before being used.  This may not scale well as we start to support many more languages, and of course there are likely some name clashes (e.g. Ruby vs. R).

We should design something that maybe places the options into a submenu without keyboard shortcut until first use in a cell, at which point it gets a keyboard shortcut.  (Or something -- open to other ideas).

**Comment by bcolloran** [comment]
this will go away with direct jsmd editing -- users will just type:
%% py
%% js
%% r
%% ruby
...

and they'll be able to insert or change a cell via the cell menu and top level menu (and perhaps command palette one day), but since typing the desired cell type will be the keyboardy way of getting the  desired cell type, we probably won't really need kbd shortcuts for those menu items.

(we can continue to to expose all the "known" languages via cell menu and help pane for discoverability-- the kbd shortcuts don't really add to our discoverability story beyond that)
