### ISSUE TITLE
saving a notebook on extremely-alpha appears to be forking instead of saving a revision

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1071]
This is a code-red bug. Something has broken the server (possibly from merging #1061, but could also be #1068) such that each notebook save forks the notebook instead of saves a revision. I have no idea how this might have happened, but we need to address it as soon as we can.

I can reproduce this on extremely-alpha, but not on my own local build.

**Comment by wlach** [comment]
I can reproduce this locally. It looks like the problem is that `state.notebookId` is no longer being set on initial load of the notebook. First likely culprit to me seems like 7cf2d8ca5dfaedc9de1c8ba378d5d740515197df, but I don't have time to track down further right now.

The "right way" of fixing this might be to dispense with `state.notebookId` and only pay attention to `state.notebookInfo`.

**Comment by hamilton** [comment]
Cool - thanks for taking a look @wlach. I'll take this on and get it fixed since I think we must have missed this in the QA on #1068. Sorry y'all.
