### ISSUE TITLE
add language drop down to iodide console

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1088]
@mdboom was asked at PyData if pyodide could actually be run in a terminal, so he [slapped together this hilariously lightweight gist](http://htmlpreview.github.io/?https://gist.githubusercontent.com/mdboom/686a05ce026f87d6005c1cc806eef0bb/raw/3d6fa10eae2313be0c7b26b381feeec15ac12ed0/pyodide_console.html). 

It brings to mind a few things:

- the console in iodide should work like a console - hitting `enter` should probably run the REPL line
- having a small dropdown to the left of the arrow which sets the language would be useful. I want to be able to type `import numpy` and start working directly in pyodide. maybe when the console line piece is active we can just use keyboard shortcuts used in the editor to set that.

![screen shot 2018-10-22 at 6 51 26 pm](https://user-images.githubusercontent.com/95735/47330003-92d26580-d62b-11e8-9341-4d676f106ba9.png)

**Comment by bcolloran** [comment]
totally, i thought of this when picking the current 'shift+enter' and 'ctrl+enter' rather than just "enter" -- was thinking a bit ahead to once we direct JSMD mode and one can execute highlighted code (like in rstudio), but i can see how it's confusing ATM.

the idea overall is to train people on the pattern "shift+enter/ctrl+enter executes code", which becomes increasingly useful when you want to edit a multiline code snippet in the console. that will come up a lot in our use case, b/c we'll be sending multiline code chunks over to the console all the time, and it'll be easy to access these multiline chunks in the console scroll back. in the normal browser console, to insert a newline one types 'shift+enter', but having that mean "execute code" in the editor and "insert newline" in the console introduces a weird reversal depending on which editor the cursor happens to be in. so for our case, i think the most parsimonious and least confusing thing is to maintain parallelism and ingrain the pattern: "shift+enter/ctrl+enter executes code"

so for now, let's leave that as is -- i think it'll make more sense when we have direct jsmd in place.

--

regarding the language drop down: yes +1 absolutely needed. i'm going to recast this issue to be just about that

**Comment by hamilton** [comment]
Sure, happy to let the focus on this issue be about the language button. Going to file a separate issue to break these two things out.

**Comment by hamilton** [comment]
Closed via #1489.
