### ISSUE TITLE
as a user, I would like a toolbar of some sort on the console

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1090]
Working with the console over a long period of time becomes pretty difficult. One way we can manage volume would be to:

- have a clear console button (#1015). This should probably _not_ clear the history stored in redux - I can see that still being relevant for forensics even when the console is very long. Could be wrong about that though.
- have a button that lets me hide the code inputs from the console, since these are one of the largest contributors to the console right now.
- have a button that lets me hide the code outputs. Could be different output _types_ you can hide, or console levels (show only info / warning / error / debug / etc)

**Comment by bcolloran** [comment]
after dogfooding this a bit, i think this should be in a menu that lives in the right hand side of the console text entry rather than a toolbar -- the tool bar just eats up a lot of our precious screen real estate for three buttons (and just one ATM)

also, I'm seeing rendering errors with the clear button on extremely-alpha and localhost with both FF and Chrome. 

![image](https://user-images.githubusercontent.com/2380975/48035454-e7400f80-e118-11e8-958d-94e905b3f84e.png)
 i'm going to take a pass at all this

**Comment by hamilton** [comment]
Let’s talk about this during tomorrow’s standup before going forward with a
change.

**Comment by bcolloran** [comment]
sgtm -- in the meantime, since this feature is not working as expected and we're not sure about the UX we want, and a couple code quality things got past review, i've reverted #1119. we can take another crack after discussing :-)

**Comment by hamilton** [comment]
Sounds good to me. fwiw I believe that issue you're encountering was brought up in that PR, which had a fix & review on my mbp on FF. Clearly I didn't do a good enough code review on this pass - apologies!

Render bugs, on the other hand, are no joke, and I'll do a better job in the future checking on Chrome.

**Comment by bcolloran** [comment]
menu exists, reopened #1015 to add a "clear console" button back in that menu. closing this one
