### ISSUE TITLE
activate POST on /new with "<my jsmd>" in the request to auto-fill some jsmd

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1100]
In sum, I'd love to be able to auto-fill a notebook that gets sent to `<server>/new`. One way to handle this would be to include in the request body the jsmd you want to use.

This will more easily allow "open in iodide"-style buttons and interactions elsewhere, from other web apps to extensions.

@wlach any thoughts about the right approach?

> maybe POST on /new with the payload that you want => prepopulated iodide notebook

**Comment by bcolloran** [comment]
@wlach @openjck -- did we complete this part of the redash story, or are any of the current PRs relevant?

**Comment by wlach** [comment]
We wound up addressing the redash story in a slightly different way (see #1642), as it turns out that one can't really just POST to iodide from a 3rd party web service on the client side and expect to have it work. We should investigate how services like https://codesandbox.io/ have made this story work e.g. from the material ui docs: https://material-ui.com/getting-started/usage/

I'd say this is probably worth keeping open for now.

**Comment by bcolloran** [comment]
hmm it looks like it might actually *not* work even from the material docs -- if you edit the code and then open in codesandbox, your edits are lost. i wonder if codesandbox makes you set up stock examples on their side and just gives an embed link

**Comment by bcolloran** [comment]
i think we have a solution for authorized POST, and that we don't actually want to support anonymous POST. we could open a new issue for POST with api keys if that turns out to be a thing that people want
