### ISSUE TITLE
Embedding iodide notebook into an HTML document

### ISSUE THREAD

**Issue by rth** [iodide-project/iodide#1130]
I was wondering if there was a preferred way for embedding an iodide notebook into an HTML document. 

Somewhat related to https://github.com/iodide-project/iodide/issues/1093 I would like to embed a few cells into a [RemarkJS](https://github.com/gnab/remark) presentation which is just an HTML document. Using an iframe works, e.g.
```html
<iframe width="500px" height="250px" src="https://iodide.io/pyodide-demo/python.html" frameborder="0" allowfullscreen></iframe>
```

However, the current limitations I have with `iframe` approach is that,
 - I'm not sure how to hide the toolbar at the top (I would like to just show a few cells)
 - when embedding it multiple times, pyodide appears to be loaded multiple times which makes the presentation a bit heavy.

It's not too critical, just wondering if there is a better way of doing this that I missed.

**Comment by rth** [comment]
Embedding the console as in https://github.com/iodide-project/iodide/issues/1090#issuecomment-436089111 would be even better. Not sure if there is a simple way of doing that?

**Comment by hamilton** [comment]
Great issue, and one we've talked about amongst ourselves. Because we do things in an iframe, iodide is severely constrained in terms of flexibility. 

Having direct jsmd editing (instead of the cell-based approach) would be one solution to your first problem. We don't have this yet, but we will soon. That would allow something like this:

```
%% md

# here is my title

%% py report-input report-output

plot(x)

```

Which should show the results of `plot(x)` (if it goes to the console) to be embedded into a report. That'd allow you to make `viewmode=report` for the iframe, which gives you the code input and output.

The second point simply cannot be done with our current approach, and this is something I've suspected would be a major drawback of moving to iframes for the actual computation engine. One way to grant the flexibility would be to move all computation from the iframe itself to a Web Worker. One thing you lose, however, is native DOM access.

I think what some users want is a computation engine that allows them to call some API like `iodide.evaluate(jsmd, domElement)` that puts the report-level outputs into that dom element, and manages the state issues elsewhere in some kind of invisible way. If one has to explicitly export to the DOM level the data (or stream of data) then we could make something like this work.

**Comment by bcolloran** [comment]
gonna mark this as wontfix -- embedding a report view in an iframe should be able to solve this at this point.
