### ISSUE TITLE
Use something other than localStorage for storing autosaves

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1144]
localStorage is slow and synchronous, we use something faster for storing local changes. In #894, @SimonBiggs recommended using the dexie wrapper for indexedb: http://dexie.org/

**Comment by SimonBiggs** [comment]
Local storage is also blocking I believe. The page will not begin to load until the entire local storage file is loaded into ram. It also has quite a low limit. There's only so much local storage this allowed to be used. IndexedDB has quite a high limit I seem to remember.

Downside of IndexedDB is it can be painful to program with. But that's where dexiejs comes to the rescue. Dexie also plays quite nice with typescript.

@dfahlander might be able to comment further.

**Comment by SimonBiggs** [comment]
To add here, I think http://dexie.org/docs/Syncable/Dexie.Syncable.js.html might also help the local changes syncing with the iodide server story.

**Comment by dfahlander** [comment]
Cheers!

The biggest step when migrating from locaStorage to IndexedDB is going from sync to async - which may impact a chain of functions that previously returned values now have to return Promises. Would really recommend using the async/await keywords to simplify this migration.

Regarding the sync part, you could either implement that proprietary, use dexie-syncable (still in beta), or [sync-client](https://www.npmjs.com/package/sync-client)/[sync-server](https://www.npmjs.com/package/sync-server) that builds on top of dexie-syncable.

I am also working on a multi-tenant sync solution to hopefully be released next year if that would be of interest.

**Comment by iFlameing** [comment]
@wlach  I am working on it.

**Comment by iFlameing** [comment]
@dfahlander  @wlach  
async function getAutosaveState(state) {
  const autosaveKey = getAutosaveKey(state)
  const auto = await db.autosave.get(autosaveKey) // I am fetching the data stored in indexDB with autosavkey as key.
  const status = auto;
  return auto;
}
But the problem is when I returning the auto it becomes promise where as when I am doing console.log(auto) it is printing the value. How should I return the fetch value i.e "auto" from this async function.
Whole code of that I modify in autosave can be find on this [link](https://pastebin.com/0nL70wC2)
