### ISSUE TITLE
Make iodide.output.element work post-JSMD editor refactor

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1216]
At the moment matplotlib will not plot on the direct jsmd editing branch (#1152). I'm not sure but it is possible that @mdboom may have to change something on the pyodide side to ensure that we have the language support.

**Comment by mdboom** [comment]
Python and matplotlib on their own seem to work fine.  (I had to change the delimiters from `%% code {"language":"py"}` to `%% py`, but I think that's on purpose.)

The issue is in the call to `iodide.output.element`.  It looks like the function `sideEffectDiv` is still doing some very cell-ish things.

```
element: (nodeType, reportSideEffect = true) => {
    const div = sideEffectDiv('side-effect-element', reportSideEffect)  <--- this returns null
    const node = document.createElement(nodeType)
    div.append(node)
    return node
  },
```

**Comment by bcolloran** [comment]
@hamilton does #1222 fix this, or do you have something else in mind? i think this can be closed now, but if we want to change this issue to be about pyodide moving away from, let's update the title and labels accordingly.

see also #1223

**Comment by hamilton** [comment]
@bcolloran, I believe it does.
