### ISSUE TITLE
in-app documentation for alpha launch

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1286]
we need to document a few things in our in-app help pane:
- [ ] jsmd in general
- [ ] jsmd fetch syntax in specific

**Comment by mdboom** [comment]
Note some existing and probably out of date docs are in the iodide-project/docs repo.

Design points (for discussion):

- Move the docs into this repo so we can start having pull requests that update features and docs in a single go.  Shut down iodide-project/docs after.

- The existing docs repo is really *cool* because it uses Iodide/jsmd to document itself.  I think maybe we aren't ready to do that feature-wise, since we'd want to have cross-notebook-linking and other nice documentation features.  But long term, I'd like to try to get back to the "dogfooding" approach where the docs exist are nothing more than special Iodide notebooks that are easily accessed from the app.  

- For that reason, as a stopgap to get something workable up now, I think it's important to use a markdown-based documentation system (instead of Sphinx or something else) for now, and not use too many of its "special" features so that it will be easy to transfer markdown content to jsmd content in the future.

- The popular choice for that appears to be GitBook, and there is the similarly featured Rust-based mdbook that is a Mozilla-supported project.  I've asked around to some folks about their expriences with Gitbook vs. mdbook, but I think I'm leaning toward GitBook given that it's node based and so is Iodide and adding Rust would be a different thing.

**Comment by mdboom** [comment]
`mdbook` looks like the right feature set, however, there is a non-zero setup cost to getting it installed which may be tricky for third-party devs, most of which will probably be familiar with the Js ecosystem, but not Rust.

Other alternatives:
- [docusaurus](https://github.com/facebook/docusaurus) Node-based
- [Markdown in Sphinx](https://www.sphinx-doc.org/en/master/usage/markdown.html) Python-based -- but supported by readthedocs which buys us a little convenience.
