### ISSUE TITLE
Docs task is failing in ci on master

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1308]
It appears that circle is failing on the docs job on the master branch. https://circleci.com/gh/iodide-project/iodide/1759

Here's the output from the above:

```
#!/bin/bash -eo pipefail
if [ $CIRCLE_BRANCH == "master" ]; then
  git remote add docs git@github.com:iodide-project/docs.git
  mkdocs gh-deploy --force --remote-name=docs --remote-branch=master
fi

INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/circleci/project/site 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - api.md
  - contributing.md
  - developer.md
  - jsmd.md
  - keybindings.md 
WARNING -  Documentation file 'contributing.md' contains a link to 'CHANGELOG.md' which is not found in the documentation files. 
ERROR   -  Deployment terminated: Previous deployment was made with MkDocs version 3.1.14; you are attempting to deploy with an older version (1.0.4). Use --ignore-version to deploy anyway. 
Exited with code 1
```

I'm not sure where it's getting `3.1.14` from? It appears that's the version of `webpack-dev-server` that we're currently using, but I don't see how that could possibly be related:

```
Hammersmith:iodide wlach$ git grep 3.1.14
package-lock.json:      "version": "3.1.14",
package-lock.json:      "resolved": "https://registry.npmjs.org/webpack-dev-server/-/webpack-dev-server-3.1.14.tgz",
package.json:    "webpack-dev-server": "^3.1.14",
```

@mdboom any thoughts here?

**Comment by mdboom** [comment]
Interesting bug, actually.  I found where `MkDocs` is doing this [here](https://github.com/mkdocs/mkdocs/blob/3f0e4464a787ad5ce5a235d7ae988a2d8f53f077/mkdocs/commands/gh_deploy.py#L54) It's checking the last version that did the deployment by looking at the git commit message of the last deployment.  However, it's looking in the source repo (iodide-project/iodide) rather than the destination repo (iodide-project/docs), and it found this commit message:

```
commit f174a2c63af9fbae75ebb030aaa8b1325bfb7068
Author: renovate[bot] <renovate[bot]@users.noreply.github.com>
Date:   Mon Dec 31 17:12:47 2018 -0500

    Update dependency webpack-dev-server to v3.1.14 (#1298)
```

I'm not sure why the version check is necessary, since AFAIK it clears out and replaces the entire generated tree each time.  I'd advocate adding the `--ignore-version` flag to our deploy command and, time permitting, try to work out an upstream patch.

**Comment by wlach** [comment]
This bug is currently preventing us from auto-deploying master to heroku (since the ci is failing), so we should probably implement the suggested stopgap fix.
