### ISSUE TITLE
Add revision browser to notebook

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1455]
I think to make saving sane (esp. in an autosave world), we should add a revision browser to the notebook interface itself. I'm going to look into building this.

**Comment by hamilton** [comment]
@wlach this sounds good to me - looking forward to seeing what you have in mind. I'd additionally suggest that:

(1) whatever we do in the notebook, let's make sure to have it in `src/shared/components` and
(2) apply the viewer to the revisions page on the server as well

**Comment by wlach** [comment]
I'm diving into the implementation -- there might be some complications with sharing the component between the server pages and the notebook interface, as the latter uses redux and the former doesn't.

I think we might want to rethink whether we want to allow management of much of the notebooks outside the notebook interface itself. I think @hamilton added the file browser, revision list, etc. there because it was easier to do so inside the server pages than inside the notebook... but now that we're moving (slowly) past the hacky prototype phase I'd like to suggest that the notebook is the correct (and only) place for such things. I don't think having multiple interfaces to that functionality is super helpful tbh.

**Comment by hamilton** [comment]
I did that originally as a way to have _some_ way of handling these things. 

Re: sharing between the two, we have other methods of sharing components that doesn't conflate the redux parts w/ the react ones. For one thing, all components in general should be unconnected, and the integration to redux should come through `connect` (sometimes exported in the same file, but in this case probably shouldn't be). That lets you use components without logic on the server (by supplying all the props to the components manually) while connecting to redux to fill in the props otherwise.
