### ISSUE TITLE
iodide console errors out when returning a python module

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1493]
This is related to the new reps. This code block breaks things:

```python
import numpy
numpy
```

**Comment by mdboom** [comment]
```
TypeError: data.propertyIsEnumerable is not a function[Learn More] ObjectInspector.js:204
```

*Could* be a bug in the Javascript Python proxy that we're just now hitting because it the different way react-inspector handles things.  Let me dig deeper.

**Comment by mdboom** [comment]
I think what's happening is that Pyodide is returning a DOM object to do a custom display of a Python object.  That fails due to recent changes required HTML strings, so it falls back on the standard Object rendering which doesn't play with with Javascript proxies.

1. Fixing #1488 should fix the immediate problem.
2. Pyodide can be updated to return a string rather than a DOM object (but I'll wait to see the determination on #1488 first in case that's not necessary)
3. The issue with proxies should probably be fixed, too, but it's not clear yet whether that's a bug to be fixed in React-Inspector or Pyodide.  It's actually a little hard to debug because just bringing the object over to the Javascript side crashes the workspace view, even if I choose not to display the value in the console.

**Comment by bcolloran** [comment]
@mdboom re #1488 -- yep, the change is intentional -- ideally, custom reps will just return html strings. My hope was that this would not be too difficult of a change, b/c we're mostly using the ipython htlm protocol, which IIUC uses html strings:
https://ipython.readthedocs.io/en/stable/config/integrating.html

but in any case: this should *not* cause the iframe to halt. So we'll tackle that bug to make the overall debugging possible.

thanks guys!

**Comment by mdboom** [comment]
Once https://github.com/iodide-project/pyodide/pull/318 is merged and a new Pyodide release is made, the basic stuff should be fixed.  We'll still need to separately tackle (3) above and see why displaying Javascript proxies is causing React Inspector to throw.
