### ISSUE TITLE
evaluation magic for object literals

### ISSUE THREAD

**Issue by runsun-edu** [iodide-project/iodide#1619]
### What I Did

Type:

%% js
{a:3,b:4}

and hit SHIFT-ENTER

### What I Expected

Showing {a:3,b:4} in the console

### What Happened 

SyntaxError: Unexpected token :

### Further observation

No error if it is an assignment statement:

%% js
d= {a:3,b:4}

**Comment by bcolloran** [comment]
Thanks for the report @runsun-edu!

I looked into it a bit, and I think this is a genuine syntax error in JS (I tried inserting `{a: 3, b: 4}` in the middle of a js file and the parser barked at me). I think that the parser begins treating the first curly brace as the beginning of a "block" in the case of a plain object literal -- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block#Description

**Comment by runsun-edu** [comment]
I recall any other javascript console would treat that code w/o error. For example, https://jsconsole.com/

**Comment by bcolloran** [comment]
Sure. It's a bit tricky and a bit of a mixed bag, actually. Executing `{a:3,b:4}` in the FF devtools gives that error, but in chrome devtools it works. Executing `eval('{a:3,b:4}')` give the error in both browsers. We think that chrome actually does some magic behind the scenes to make this work, but that it's kind of "non standard". I guess i'll reopen this, because I suppose we could look into it own the line. It would certainly be convenient to just write object literals like that in some cases. But realistically I doubt we'll get to it anytime soon, b/c we are very wary of adding any magic around our js evaluation, and the complications that doing so may introduce.

Again, many thanks for the report!! :-)

**Comment by runsun-edu** [comment]
That's true. I guess it's not that critical anyway.
