### ISSUE TITLE
»Webgl is not supported by your browser« in Brave, although it is supported

### ISSUE THREAD

**Issue by Xjs** [iodide-project/iodide#1627]
Opening https://alpha.iodide.io/notebooks/34/?viewMode=report in the Brave browser (https://brave.com, it's based on Chromium) yields »Webgl is not supported by your browser - visit http://get.webgl.org for more info«. Going to http://get.webgl.org in Brave, however, says »Your browser supports WebGL« and successfully displays an animation.

It would be nice if WebGL visualisations inside iodide notebooks would work in Brave.

**Comment by bcolloran** [comment]
Hi @xjs, thanks for the bug report. I think this is probably an upstream bug and not something specific to Iodide, because we don't do anything that should interfere with WebGL in the code we. I wonder if there is a problem with plotly in Brave. Would you mind visiting https://plot.ly/javascript/3d-line-plots/ to see whether that works correctly?

**Comment by Xjs** [comment]
That doesn't work already. Thanks for pointing me in this direction, I opened https://github.com/plotly/plotly.js/issues/3640.
