### ISSUE TITLE
Iodide + Nginx Href = false

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/iodide#1701]
Short summary of the bug. Please include the IODIDE version number where you found the bug - if you are just running locally (building for dev or prod) you can put MASTER

### What I Did
I installed the newest MASTER version of Iodide.
Changed the port and url.  Built it. 
I fired up an NGINX server.  You can see my NGINX config file at the bottom of the page. 
It has the commands to define the WASM content type.

code sample or exact steps that causes the bug
You can see the demo here. 
http://iodide.pythonlinks.info/iodide.dev.html

### What I Expected
This is exactly what I expected to happen.  I had the exact same problem with 
npm run start-and-serve.  But I thought it best to demonstrate with NGINX.  

### (if applicable) notebook that reproduces bug 
> The smaller the better 

Small s a great idea. In due course I will poke around and try to figure out more as to what is wrong, 
but I thought the experts could probably take one look at this, and would know the problem instantly. 
Here is the NGINX Code.    If you want I could create a pull request to include that int he documentation. 

server {
       listen 80;
       server_name  Iodide.PythonLinks.info;
       include sites-available/favicon.conf;

    location / { root /home/lozinski/code/cromlech/iodide/build/;
    }
    location ~* \.wasm {
         default_type application/wasm;
        root /home/lozinski/code/cromlech/iodide/build/;
     }
}

**Comment by PythonLinks** [comment]
Problem Solved.  

Every notebook has to have the noteookInfo JSON available. 

At the bottom of this page is my iodide.dev.html file. 
That is after running npm run start. 
No notebook info.  So it crashes.  

I guess that means that people are not using the npm run-and-serve. 
Everyone is focussed on the Django Server. 

But think about the market.  The big competitor is Jupyter Notebooks.  For that you need not just a file server, but also a compute server.  That does not scale.  It does not work for schools or any group with 
thousands of users. 

The brilliant thing about iodide is that all that you need is an nginx server.  Schools could start using it right away.  Except that the basic file serving is not working. 

I hope that helps. 
Chris






<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>new notebook - iodide</title>
<link rel="stylesheet" type="text/css" href="https://dev.pythonlinks.info//iodide.dev.css">
<base target="_blank" rel="noopener noreferrer">
</head>
<body>
<script id="jsmd" type="text/jsmd">

</script>
<iframe
  id="eval-frame"
  src="https://dev.pythonlinks.info//iodide.eval-frame.dev.html"
  sandbox="allow-scripts allow-same-origin"
  allowfullscreen="true"
  allowvr="yes"
></iframe>
<script src="https://dev.pythonlinks.info//iodide.dev.js"></script>
</body>

**Comment by bcolloran** [comment]
thanks @PythonLinks -- you're right, we are focused on the server. we're hoping to build up iodide.io to be something that schools can use without needing to run any kind of server whatsoever, ever a "simple" nginx server, because even that is complicated for a lot of people to set up.

also, for background: we initially started with a "simpler" file-based approach, but because of some limitations inherent to the browser, we were never able to develop satisfactory workflows for even the simplest of tasks... like saving your work. we decided we needed to shift directions, and started building our django server component to deliver the kind of frictionless experience we have found lacking elsewhere: no installation, just open a URL and get started. so we're going all-in on trying to build iodide.io as an open source commons for public scientific computing, data science, and data viz. we know that not everyone will agree with that bet, because many people want something that they can run on their own computer like jupyter... but that's the bet we've made. :-)

anyway thank you for your interest and your support!! :-)

**Comment by PythonLinks** [comment]
Thank you for that critical information. 

I totally understand your thinking.  The mass market is education.  They need a solid server.   

Allow me to express a different opinion.  A marketing opinion, as opposed to a developer opinion.

The educational market is a possible future market.   But it has very little money to spend.  There is no ”business model”.  Even non-profits need a business model. 

Then there is the issue of backward compatibility.  The reason Microsoft and Intel did so well, was because of backward compatibility. 

>  you're right, we are focused on the server. 

My advice would  be to focus  on your potential customers, rather than on the server. .  Who would want to run data science libraries in the browser?  Existing Jupyter Notebook users with slow compute servers.   

I would think that if you could run a Pyodide server as part of a Jupyter notebook, a number of Jupyter Notebook users would start using this project. Money would flow from some big corporations. 

Even though it has not been updated since October,  and the Python demo is broken, I should mention Jyve
https://github.com/deathbeds/jyve

They work with Jupyter Lab, and allow you to run a number of different kernels in an iFrame.  It is an interesting idea.  I wonder why they are not under active development?

**Comment by bcolloran** [comment]
thanks for the the thoughts @PythonLinks. Have you seen the blog post from a couple months back?-- 
https://hacks.mozilla.org/2019/03/iodide-an-experimental-tool-for-scientific-communicatiodide-for-scientific-communication-exploration-on-the-web/

That should give you some insight into who we're thinking of as our "customers" and the wrkflow issues we're trying to solve for those people.

(and just to be clear: when i say "we are focused on the server" it is only in contrast to focusing on file-based workflows, which  we have already tried and found to be lacking :-/ but please understand that we are only working on the server component because it turned out to be necessary to support the product requirements of our "customers". which _is_ our focus, as you rightly suggest is should be!)
