### ISSUE TITLE
is using %% for cell separator a good idea?

### ISSUE THREAD

**Issue by shi-yan** [iodide-project/iodide#1821]
I think %% in the jsmd format isn't a good choice. Both Latex and Matlab code use %% for their comment block, this could confuse a jsmd parser.

Although jsmd doesn't support them yet, the use of %% prohibits future integration. Both Latex and Matlab are huge in academia.

**Comment by bcolloran** [comment]
hi @shi-yan, thank you for your interest in iodide!

choosing a delimiter like this is definitely challenging because of the potential collisions that might occur. I'm not sure any choice would be free from collisions (at least not any reasonable choice -- something succinct and visually clear), but we chose "\n%%" because two percent signs at the start of a line doesn't have collisions in any of our core languages, and in very few languages in general.

In fact, we chose "%%" following MATLAB's cell syntax -- it's not a problem in that context, because you can use a single "%" for a comment, or as many "%"s as you want as long as they are not at the start of a line. Likewise, in LaTeX, you can use a single % for a comment rather than a "%%", as well as being able to use things like 
```
\begin{comment}
Commented code
\end{comment}
```
from the verbatim package.

Thus, these particular collisions are also not severe enough to make us wish to change the block delimiter, and there are easy workarounds, so future integration won't really be materially prohibited.

We'd really welcome LaTex and Octave integration! (MATLAB will never be possible, b/c it is proprietary and closed source). If you feel like contributing to a language plugin for either, we'd love to support that!
