### ISSUE TITLE
Notebook history should be inaccessible in "try it" mode

### ISSUE THREAD

**Issue by ZiyaoWei** [iodide-project/iodide#2114]
On https://alpha.iodide.io/tryit/, if I go to `History` without logging in, the popup shows `Error getting revisions` - should this be changed into something friendlier?

### What I Did

Open a browser tab in Incognito mode, go to https://alpha.iodide.io/tryit/, click on `History`

### What I Expected

Maybe something along the lines of "Please login to save your work"?

### What Happened 

`Error getting revisions`

### (if applicable) notebook that reproduces bug 

link to the notebook that reproduces the bug. the smaller the better. you may wish to use https://definitely-staging.iodide.io/ (our staging environment, deploys from master) for creating/sharing the notebook.

**Comment by ZiyaoWei** [comment]
Mmm, maybe I got too excited and this is caused by an error from the backend?

**Comment by wlach** [comment]
This is definitely a bug! We should probably disable the revision browser item on trial notebooks, since there is no history to get. You can make this conditional on whether we're in "try it mode". 

Do you want to take this on? It's probably not a bad good first issue.

Hint: You can use this function for detecting whether we're in try it mode:

https://github.com/iodide-project/iodide/blob/fc048a5d1ae364a13ef2417c712c4868244dddc4/src/editor/tools/server-tools.js#L75
