### ISSUE TITLE
Support PWA capabilities for Iodide

### ISSUE THREAD

**Issue by teonbrooks** [iodide-project/iodide#2231]
As a user who is starting to use my iPad more and more and with Apple's recent decision to bring a desktop-class browser to the iPad with iPadOS, and with the development of support for PWAs across platforms, I think Iodide would be poised to support PWA.
A few added benefits include:
- the ability to work on notebook when not connected to the Web
- cache python resources in the web app
- give a native-like app feel without high developer cost

I have expressed some interest in working on this @wlach but if someone else would like to take a crack at it, please feel free!

**Comment by bcolloran** [comment]
sounds interesting @teon! if you are interested in looking at this, i think you should go for it :-)

do you have a sense of what kind of constraints this might impose to make it work? wrt an offline mode, would we need to revamp the way saving is handled? (@wlach i guess you might have thoughts on that?)

**Comment by wlach** [comment]
Lots of possibilities here, ranging from very easy (e.g. adding an "app icon" for iodide) to medium-complex (caching server-side assets locally for faster load times) to complex (allowing *everything* to work offline). I'd recommend reading through some of the online resources on service workers to get a better sense of how this might work. e.g. :

https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API
https://developers.google.com/web/fundamentals/primers/service-workers/

This issue is probably better broken down into a smaller set of tasks. @teonbrooks -- this might be a good thing to discuss in next week's iodide meeting if you'll be available then.
