### ISSUE TITLE
break out handlers into separate files

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#276]
The handlers appear to all be in `output.jsx` out the moment, which could grow unwieldy as we add more handlers. Doing this would make it easier to just let `CellOutput` be a vessel for the handlers defined in other files.

Unless I'm missing something. `ExternalResourceCell` has a special type of output that isn't really applicable in other cells, and I think that's probably a good thing, but just trying to figure out how to square this with the current approach.

I could:

a. make a special `externalOutputHandler` and square it with the current `CellOutput` implementation (specifically around checking for certain structure to the value) before it is selected, or
b. make a whole other custom component type for the `externalOutputHandler` and leave the `CellOutput` as-is. This is the approach taken in `MarkdownCell, roughly`. If we go with this direction (which I'm not averse to) I would maybe suggest we rename `output.jsx` to reflect that it is primarily for javascript cells.

For #272 I'm going to pursue b given the example in `MarkdownCell`. All the same, as we add more output handlers into the core, it still might make sense to decompose that file.

**Comment by bcolloran** [comment]
does #288 have implications here (since we probably want to move this to a stdlib function)? note that in the paradigm described in #288, i think touching the store and depending on the normal React life cycle won't work, since we're proposing manipulating the DOM directly within an eval call; in that case, we'd need this output to render as a much simpler HTML or text string that we can directly append to the DOM with an `innerHTML` call (which might also just be a flaw in the #288 proposal).

**Comment by bcolloran** [comment]
summary: each output handler should live in a separate file as it's own react component
