### ISSUE TITLE
make sure that all content from our presentation deck is available in written form

### ISSUE THREAD

**Issue by metasean** [iodide-project/iodide#281]
The readme.md references a slide deck, but then that slide deck requires permission to be accessed.

### What I Did

followed the readme.md's "see our slide deck" link

### What I Expected

to see the slide deck

### What Happened 

google drive told me "You need permission" to see the slide deck  (yes, of course, I could have requested permission, but that wouldn't help anyone else who sees the readme.md link and expects to actually be able to see the referenced slide deck when they follow the link)

**Comment by hamilton** [comment]
I'm going to add @bcolloran to this issue to see what he'd like to do here. Our plan is to flesh out the `Motivations.md` file to keep the motivation, origin story, and philosophical approach all in GH. The easier plan is to make the slide deck public, and I guess update it, since this is a public project now.

**Comment by bcolloran** [comment]
i looked back at the deck, and i think it's actually confusing without me explaining things verbally. I'll delete that reference from the readme, and change this issue to be sure that we go back and include all of that same content in written form (FWIW: we have almost all of it already)
