### ISSUE TITLE
iodide needs a stdlib for common notebook-centric operations

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#288]
we've talked for a while about having a small library of built-in functions; following from our discussion the other day, i think our approach will feel more unified (most stuff happens in code, not in special cells), and our app code will be simplified a bit if we move things to a set of library functions that are called within the normal eval paradigm.

These are just a few ideas to get the conversation rolling (we can pick any namespace we think works best, but in these examples i'll just use `io.`; could also be "IO.", "iodide.", "nb.", "NB.", etc) --

`io.DOM(elt type, elt attrs, showInPresentation = true, ???)` - immediately create and return a reference to a DOM element (dangerously mutating the DOM outside of the react flow-- i *think* we can get away with this, b/c muting DOM within MD elts seem to work ok, even when you trigger re-renders of parent elts by e.g. moving a cell up/down). This would append a new child to a div that we would add to each cell (between the input and output rows), and which could be selected by e.g. `document.body.querySelector("div.cell.selected div.printarea")` or whatever.

`io.print(obj, showInPresentation = false)` - extension to `io.DOM` that would print `obj` into, let's say, a `<pre>` container? note that i don't favor globally overriding or somehow capturing `console.log`. i believe we should whenever possible avoid changing _anything_ about the behavior of regular browser APIs unless we have no choice, and this is a perfectly legible alternative.

`io.show(obj, showInPresentation = false)` - extension to `io.DOM` that would pretty print `obj` using any registered output renderers.

`io.script(url)`; `io.stylesheet(url)` -- request a script or stylesheet and do whatever we currently do (just append a <script> or <link css> tag in <head>?). we could also offer something like `x = io.script(url, namespace=true)` that returns an object containing everything that is dumped into the window object when you load a script via script tag. i'm wary of using the term "require" because i think it implies dependency resolution or something (but i'm not sure about that)? or maybe `io.require` would be used for files wrapped in module syntax? i'm really not sure how this stuff works.

`io.getFile(url, timeOut = 5000ms)` or `io.awaitFile(url, timeOut = 5000ms)` -- synchronously load and return data object. flags for parsing csv, json, ... ?

`io.registerTranspiler(url, transpilerKeyword)`registers a transpiler to be run on the input content of a cell before passing the content to `eval`. `transpilerKeyword` is some string that, if present on the first line of the input, runs the input through the transpiler. e.g., it might be "use math" for math syntax sugar, "use jsx" to use the normal jsx transpiler, and so on. 

curious what ppl think of this idea and if it makes sense, what other utility functions would we want create?

**Comment by hamilton** [comment]
I have been thinking about this as well in a somewhat similar fashion, especially in light of `console.log` and discussion of output handlers more broadly. All for the idea generally.

some unfinished thoughts about the approach:

- though it would be great to use `io` as the ns, it would unfortunately collide directly with the `socket.io` namespacing paradigm, which is pretty popular. Definitely think a two-letter ns is a good idea vs `iodide`. Room to explore ideas here.
- getting rid of the `ExternalResourceCell` would be great because that workflow does kind of break the paradigm of code-or-markup-for-everything, which we should stick to as much as we can.
- we can easily use the new output handler for external resources I'm putting together, returning the new globals just like we would for `print` generally, along with an option to suppress output.
- if we weren't going with a core lib I would argue for reforming `console.log` is totally acceptable, but I'm all in favor of a `print` that explicitly does what we want and leave `console.log` untouched in this context.
- This lib should definitely be it's own project with repository, tests, and GH issues (and as such I'd be in favor of simply making the repository right now and putting this issue discussion there)
- This should be developed as a dependency that makes it into `iodide`. I'm not sure what utility this would have outside of `iodide` the IDE as of this writing, but that is something worth discussing down the line, and keeping it a separate repository allows separation of concerns so we can cross that bridge when we come to it.

Definitely more to talk about. Will put it on the agenda.

**Comment by hamilton** [comment]
it might be nice to spend a minute longer thinking about if this approach would potentially help us against #157. I don't really know. It DOES seem like solving this would require something like the `ignoreModeKeybindings` kv pair as a way of powering off whatever mode you were in, and you could enforce that upon hover of your svg or something. Pretty tricky!

**Comment by bcolloran** [comment]
@mdboom i know you've been thinking about public APIs in #244, any thoughts about that in this context? Would introducing something like e.g. `io.registerOutputHandler(...)` be helpful do you think, or is it at cross purposes? Having both options available might also be desirable -- i like following the tested pattern used in the Python projects you mentioned.

**Comment by hamilton** [comment]
@bcolloran it'll be great to circle back on some of this soon.

**Comment by bcolloran** [comment]
@hamilton sure. which bits in particular do you want to circle back on?

**Comment by bcolloran** [comment]
closing. last bit is in #719
