### ISSUE TITLE
[META] add some onboarding for first-time notebook users

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#317]
Inspired by #315 - new user completely baffled about what the heck to do.

- there is no way for new users to know what to do first when they're dropped in a notebook.
- there is no indication of what they can put in a cell when they're dropped in. This would be fixed by both default gray-out text and #312 / #187 
- we should make it easy to get right to links, guides, etc. when they're in the notebook.
- any annotations should be hideable with one click such as "I'm good - don't show this again"

**Comment by bcolloran** [comment]
I'm working on this right now

On Feb 12, 2018 4:33 PM, "Hamilton Ulmer" <notifications@github.com> wrote:

Inspired by #315 <https://github.com/iodide-project/iodide/issues/315> -
new user completely baffled about what the heck to do.

   - there is no way for new users to know what to do first when they're
   dropped in a notebook.
   - there is no indication of what they can put in a cell when they're
   dropped in. This would be fixed by both default gray-out text and #312
   <https://github.com/iodide-project/iodide/pull/312> / #187
   <https://github.com/iodide-project/iodide/issues/187>
   - we should make it easy to get right to links, guides, etc. when
   they're in the notebook.
   - any annotations should be hideable with one click such as "I'm good -
   don't show this again"

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iodide-project/iodide/issues/317>, or mute the thread

**Comment by bcolloran** [comment]
closed with #377
