### ISSUE TITLE
Re Eval based on the current state of notebook

### ISSUE THREAD

**Issue by pbteja1998** [iodide-project/iodide#326]
Short summary of the bug. 
Bug is at MASTER

### What I Did
1. Add a = 10 as first line
1. Add b = a as next line
1. Now remove first line
1. Evaluate second line

### What I Expected
- `Reference Error: a is not defined`

### What Happened 
- It has been evaluated to `10`

### What is causing the bug
Whenever a cell is cleared, the variables are not being updated as per the code that is present in the notebook.

**Comment by bcolloran** [comment]
Hi @pbteja1998, the behavior of Iodide is modeled on the Jupyter Notebook; code must be executed to change the execution state, and as of now code is executed by cell, not by line. Did you add `a=10` and  `b=a` in separate cells or were both lines in one cell? Did you evaluate between steps (1) and (2)?

Clearing a cell will not cause the variables to be deleted. You can see all the variables currently declared in the notebook scope by pressing  `ctrl+d`. Please let us know if we can answer any further questions!

**Comment by pbteja1998** [comment]
Yes, I have added `a=10` and `b=a` in separate cells. I have evaluated between steps 1 and 2. 

But intuitively, clearing a cell should clear the variables, right? Why are you not clearing it? (atleast we should delete the cleared variables by the time of next evaluation, isn't it?) is there any reason for not doing this?

**Comment by bcolloran** [comment]
Oh I understand now. The evaluation model we're trying to duplicate is that
of the Jupyter notebook. Executing a cell updates the global evaluation
state. At this time, a "reactive programming" approach like that used by
the "Observable" project or "Carbide" is out of scope for us

On Feb 13, 2018 12:00 AM, "P Bhanu Teja" <notifications@github.com> wrote:

Yes, I have added a=10 and b=a in separate cells. I have evaluated between
steps 1 and 2.

But intuitively, clearing a cell should clear the variables, right? Why are
you not clearing it? (atleast we should delete the cleared variables by the
time of next evaluation, isn't it?) is there any reason for not doing this?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/iodide-project/iodide/issues/326#issuecomment-365179943>,
or mute the thread
