### ISSUE TITLE
CSS might have regressed without bootstrap reset and basic styles.

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#331]
might be worth seeing whether we like the basic bootstrap styles (without all of their crazy buttons and grids and stuff). Presentation mode is looking a little shabby

**Comment by hamilton** [comment]
Yes! This was a big part of the motivation for #237, though we've had issues with the presentation mode styling since well before we had bootstrap, iirc. we had discussed having a stylesheet specifically targeting presentation mode that 1.) we can use as a template for different built-in styles (NYT data journalism, dashboard, etc.) and 2.) others can use as guides for their own custom style sheets.

I'd be all for having some parts of bootstrap be the standard, but the stylesheet `in toto` does so many funky things to this app, that we should not bring in the whole thing.
