### ISSUE TITLE
what to call to import the notebook stdlib

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#350]
re #343, what do we want to call the notebook stdlib?

First, an aside -- the other day we discussed whether it would be better to just make the stdlib available i the window scope by default, or whether we should require an explicit import. The latter is nice because explicit is better than implicit; the former is nice b/c these functions will likely be used a ton, so always importing them could look like boilerplate. But thinking about it more: is the point moot because js doesn't have a native "import" or "require" function? So there will be no way to make the stdlib available unless we include a function like that, and we we're thinking we'd include that in stdlib so that we can remove external resource cells (see #288). So it seems like we'll have to just put stdlib in the window scope, right?

So what to call it? Please toss out options; here are just a few --
`io` - seems like a natural choice, but is used by another popular library. in this case, we could require users to explicitly use another name (`socket`?) for socket.
`iodide` - and have examples where we just set `io = iodide` at the top of the notebook, just as people always import numpy as np. it's a bit of boilerplate though,
`IO` - just use caps to avoid stepping on socket
`nb` - probably another obvious choice

Would be great to get the sentiment of a few people that do a lot of JS, so at least @hamilton @wlach. I'm with @mdboom -- i don't have a sense of the js ecosystem, or how common it is for projects to have conflicting default namespace choices.

**Comment by hamilton** [comment]
Agreed w/ your assessment re: implicit vs. explicit, and would also just say that even if we had some sort of `import` functionality I'd much rather just have these be available in `window` by default, since it's just much easier for non-programmers to just accept that this ns is part of the physics of the thing.

Re: namespace / `io`, I would say that most folks (programmers and barely-programmers) who use socket.io use both `socket` and `io` as namespaces in the same files / applications following the site's documentation, and client-side the `io` namespace will be added directly if we are importing socket.io in our current way, so `io.script("cdn.biz/version/socket.io.js")` would eat `io` once the script has loaded. [This example](https://socket.io/docs/#using-with-node-http-server) outlines a pretty simple / typical example of how those namespaces are used.

Outside of that, I don't have a strong pref, but would be in favor of `iodide` or `IO` I guess. Will let @wlach chime in here if he has any feelings, and I'll think about it more on my own in the next 12hrs.

**Comment by wlach** [comment]
I think @hamilton summed it up. :)

**Comment by hamilton** [comment]
We are going with `iodide` - it's not THAT verbose, and it's very very clear that this is the namespace for the notebook of the same name.
