### ISSUE TITLE
import from gist url, export to gist

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#361]
This is a follow-on from #194 that will ease the `localStorage` deprecation in #351. @wlach had a good idea about cheaply providing a way to read the notebook contents from a gist, so we could actually point folks to, say, `iodide.github.io/master?gist=<url>` or whatever, and iodide can just grab the gist and get the jsmd contents directly.

This is about as close to providing runnable gists as anyone's gotten at this point.

**Comment by bcolloran** [comment]
💯!!

have wanted this for so long!! some ideas about a couple of the details--

- the "export to gist" function should export the whole HTML bundle (not just the jsmd) so that users can download/save the raw gist and it will Just Work if they open it as an HTML file from their local machine. this will mean a little extra footwork around pulling the JSMD out of the html, but it shouldn't be a big deal.
- @hamilton, i think this is what you meant, but just to be sure: the api can be even a bit more generic: `any/location/any_notebook.html?gist=<url>` should work to load the notebook gist indicated -- you shouldn't in specific need the notebook to be hosted at `iodide.github.io/master` or anywhere else. This would also be another way to satisfy @mdboom's workflow bug at #345 -- in dev mode, you would just locally load `dev/iodide.dev.html?gist=<url>`, and you'd get the JSMD for the notebook you want but using the js/css resources for your local dev version.

Is it possible to overwrite gists? Would a user need to be logged in or something? (It would be worth it to figure that out if it meant that you could just use gists to seamlessly save the latest copy of your code to a stable gist URL whenever you press `ctrl-s`)

**Comment by mdboom** [comment]
There's a Jupyter extension for doing this that I've been doing a little maintenance on recently: https://github.com/mozilla/jupyter-notebook-gist

It should be helpful for outlining the steps necessary to authenticate and load/save gists etc.

Also, gists can have multiple files, so maybe it would be possible to export the raw jsmd alongside the bundled html/js/css that is able to load it.

**Comment by hamilton** [comment]
@bcolloran yep `anywhere.com/whatever_notebook.html?gist=<url>` should always work.

**Comment by bcolloran** [comment]
@hereisnaman, you expresses interest in working on this in #351 -- would you like to give it a try?

Here's my proposal for an initial set of requirements; these are sorted by rough priority.
### saving to gist
- A user should be able to save gists to their git account. For now, let's use the kbd shortcut `ctrl+g`; in the future, we may want to replace `crtl+s` with this action for users that opt-in somehow.
- the gist should use the existing export functionality (i.e., a full iodide.html file should be saved to the gist)
- if a the notebook has already been saved to a gist, `ctrl-g` should update that existing gist. 
    - eventually, we may want to add "save as" style functionality; e.g. `ctrl+shift+g` allows you to target a new gist rather than updating the existing gist, but this is lower priority
- since a gist can have multiple files, after initially being saved to a gist, a notebook should also keep a backup/autosave file in the gist (which can be updated every few minutes)

### saving to repos
- a logged in user should be able to save a notebook to a specified *repo*, not just a gist. In particular, this will be important for enable people to share work within private repos.


 ***

I think the hardest part of this will be getting authentication to work nicely, and then the rest should be easy. I think that the challenge might come from the fact that this has to work no matter where the Iodide app is opened, so as you're working on this, be sure to test that the authentication works whether you open the file from a local directory on your machine (and remember to try multiple directories!) or whether you open the file from a server.

Don't worry too much about a slick UI initially; we can refine that as we go. Initially, a simple pop-up or pop-over will be fine for prototyping in a branch. But @hamilton might know about a nice way to do this using the react material ui library.

If you can just get authentication and simple saving of gists working as a demo, that would be a great first PR on this project.

Also, if you are having a hard time implementing this proposal (for example, if it turns out to be difficult to authenticate from an html file loaded from your desktop or something like that), please write up your findings in as much detail as you are able.

Thanks!! :-)

**Comment by hereisnaman** [comment]
@bcolloran thanks for the chance. I am starting with researching and working on it.

**Comment by hereisnaman** [comment]
@bcolloran a backend in must for OAuth authorization as basic authorization method won't suffice.

## Need for a backend
Read https://goo.gl/8cYFwV for Github authorization workflow. We can't leak the app's client_id and user specific access_token to the public. Also we need to save the access token somewhere for working with the api every time.

- OAuth authorization and authentication
- Integration of multiple git platforms with a single account

## Export, Import and Sharing
About exporting to and importing from local system I have a few things in mind. I am confused about what format to save the data in.
#### HTML
**Pros:** sharing without network access.
**Cons:** integration with gists, cloud storage and backend is not possible as we can't allow CORS other than iodide.com and also on http. 

I guess the reason we are using html is to support offline working. That can be easily done using service workers, iodide.com will work offline too.
### Work Offline
We can rather support sharing based on urls when integrated with gists or cloud storage and if someone still have to do actual file sharing thing we can handle that in form of json and support import from iodide.com, the only requirement will be for the user to open iodide.com just for once earlier.

I think our focus is to provide offline experience for the web app. If we want to build it like a complete offline desktop tool, we can build a separate cross platform app or browser extension app for it.

So for import and export anywhere either it be a gist or cloudstorage or local file system json will be a good go. And offline experience by making the web app work offline.

## Building the backend
@bcolloran as it is a big task, if you think we should go with it, as it is needed, we can discuss about the technical specification and the workflow further.

**Comment by bcolloran** [comment]
I need to think about this a bit. The point of exporting to HTML is more than just to allow offline work -- we also want allow a notebook to be downloaded as a fully self-contained and reproducible bundle that doesn't depend on a server component at all.

The objectives i have in mind are:
1. *frictionless* -- we're need to support the case when a scientist sends a notebook to a semi-technical or technical but busy collaborator, who might have the skills to extend a notebook, but won't bother to do so unless there is **absolutely zero** friction. you open a notebook, whether it's on your local machine or served off a website, the core functionality works.

2. *reproducible* -- we want to solve problems around reproducibility, which means that the notebook needs to be _self-contained_; it needs to either directly include all of the assets required to run it directly in-line, or it needs to point to unambiguously versioned permanent resource urls.

3. *file-oriented* (and _text oriented_) we want Iodide to work well with existing workflows they already know. We start from the assumption that in scientific workflows, people are very familiar with file-oriented workflows, and we don't want to reinvent the wheel (and the whole mental model) for people who know what they want their workflow to be like. this implies that people should be able to move files around and organize them into folders as they see fit for their projects and workflows, and that they should be able to do things they already understand, like emailing files back and forth, saving zips of them and uploading them to dropbox or whatever. we can also improve upon the jupyter experience here: in jupyter, if you are looking at a .ipynb file in your OS file explorer, (or if you get one as an email attachement or whatever), you can't just double-click it to open it like you can with a word doc. A self-contained HTML bundle allows a user to just double click the file anywhere on their system and have it open in their browser. ((Note also that we need these files to be text-oriented so they'll work with commonly used tools for manipulating text; most importantly: version control, diff tools.))

4. *decentralized* -- we don't want people to need have a relationship with iodide.io (or any other particular website) for the notebooks to work and be useful. We want user to be able to use iodide to work on data and projects that need to be hosted entirely on-premises (this includes a huge variety of use cases -- HIPAA compliance, stealth-mode anything, NDA'ed stuff).

That said, we *can* require that users either (a) install a small WebExtension or (b) be working on a notebook at Iodide.io for more advanced functionality.

We're definitely trying to create a kind of weird product here -- it's really a hybrid desktop/web app that is trying to accomplish some really unusual objectives. But coming up with creative solutions will be fun :-)

I think I'd favor the webextension approach first (to focus on the client/desktop functionality of the application -- at this point, the focus is on providing something that can plug into the workflows of people comfortable with Jupyter, though that may change). I suspect that it might be possible to build a webextension that just needs to be authorized once, and can thenceforth handle uploading to github. I believe a webextension would also allow us to handle saving to the filesystem in a much more elegant way (i.e., in a way that feels like a native desktop app)

@hamilton @mdboom @wlach -- any thoughts about this overall? Any of you know anything about web extensions?

@hereisnaman agreed, this is starting to sound like a big task  ;-)  are you up for looking into webextensions, or does this sound less interesting? No problem if you're not up for it, you should work on things that sound fun to you :-)

**Comment by bcolloran** [comment]
I need to think about this a bit. The point of exporting to HTML is more than just to allow offline work -- we also want allow a notebook to be downloaded as a fully self-contained and reproducible bundle that doesn't depend on a server component at all.

The objectives i have in mind are:
1. *frictionless* -- we're need to support the case when a scientist sends a notebook to a semi-technical or technical but busy collaborator, who might have the skills to extend a notebook, but won't bother to do so unless there is **absolutely zero** friction. you open a notebook, whether it's on your local machine or served off a website, the core functionality works.

2. *reproducible* -- we want to solve problems around reproducibility, which means that the notebook needs to be _self-contained_; it needs to either directly include all of the assets required to run it directly in-line, or it needs to point to unambiguously versioned permanent resource urls.

3. *file-oriented* (and _text oriented_) we want Iodide to work well with existing workflows they already know. We start from the assumption that in scientific workflows, people are very familiar with file-oriented workflows, and we don't want to reinvent the wheel (and the whole mental model) for people who know what they want their workflow to be like. this implies that people should be able to move files around and organize them into folders as they see fit for their projects and workflows, and that they should be able to do things they already understand, like emailing files back and forth, saving zips of them and uploading them to dropbox or whatever. we can also improve upon the jupyter experience here: in jupyter, if you are looking at a .ipynb file in your OS file explorer, (or if you get one as an email attachement or whatever), you can't just double-click it to open it like you can with a word doc. A self-contained HTML bundle allows a user to just double click the file anywhere on their system and have it open in their browser. ((Note also that we need these files to be text-oriented so they'll work with commonly used tools for manipulating text; most importantly: version control, diff tools.))

4. *decentralized* -- we don't want people to need have a relationship with iodide.io (or any other particular website) for the notebooks to work and be useful. We want user to be able to use iodide to work on data and projects that need to be hosted entirely on-premises (this includes a huge variety of use cases -- HIPAA compliance, stealth-mode anything, NDA'ed stuff).

That said, we *can* require that users either (a) install a small WebExtension or (b) be working on a notebook at Iodide.io for more advanced functionality.

We're definitely trying to create a kind of weird product here -- it's really a hybrid desktop/web app that is trying to accomplish some really unusual objectives. But coming up with creative solutions will be fun :-)

I think I'd favor the webextension approach first (to focus on the client/desktop functionality of the application -- at this point, the focus is on providing something that can plug into the workflows of people comfortable with Jupyter, though that may change). I suspect that it might be possible to build a webextension that just needs to be authorized once, and can thenceforth handle uploading to github. I believe a webextension would also allow us to handle saving to the filesystem in a much more elegant way (i.e., in a way that feels like a native desktop app)

@hamilton @mdboom @wlach -- any thoughts about this overall? Any of you know anything about web extensions?

@hereisnaman agreed, this is starting to sound like a big task  ;-)  are you up for looking into webextensions, or does this sound less interesting? No problem if you're not up for it, you should work on things that sound fun to you :-)

**Comment by hereisnaman** [comment]
@bcolloran first of all I am up for any task which makes this project helpful for that users 😄. I have less knowledge about the  scientific workflows. We will definitely build it that way that it won't disturb the work flow of the people. Thanks for your inputs, I totally understand the thing now.

Give me some time to explore if we can provide the backend integrity feature with the use of an extension. Also I will work on doing live file editing, when a locally saved html file is open, currently the user have to do save as thing again.

We can research and discuss more about this. I think you are fine with the backend part and the requirement. We can start with it while we finalise the format for the exports.

**Comment by wlach** [comment]
We discussed this a bit during the meeting. I had a look and can confirm that interacting with github's API does not seem possible with a client-side app: 

* https://github.com/prose/gatekeeper
* http://blog.vjeux.com/2012/javascript/github-oauth-login-browser-side.html

Interacting with github's API inside the web extension is probably possible, but might get kind of messy and require the user to input their credentials. As an alternative, I might propose an extension which just opened gist.github.com and pre-filled the various fields with the notebook's contents -- this will likely be significantly easier to implement, as well as being somewhat more secure. Note that a user doesn't even need to be logged into github to use this interface.

**Comment by wlach** [comment]
Oh also, if the extension *isn't* installed, maybe we could make the user's life easier by autocopying the contents of the notebook to the clipboard, so they can manually post to gist.github.com (or wherever they like).

**Comment by hereisnaman** [comment]
@wlach using the basic auth method and making the user input their credentials, is I guess not the best way. Anyways we will need to store the authorization token somewhere as we have a lot of use cases and can't ask the user to fill credentials every time. As we will be needing a backend then we should rather go with the OAuth so that user don't have to fill credentials on our end.

**Comment by hereisnaman** [comment]
I am thinking of the gist feature is not just like another export but a continuous sync and integration with the platform and we can provide much more features using the gist revisions and clone/fork capabilities. https://github.com/iodide-project/iodide/issues/351

**Comment by wlach** [comment]
Did some more research and it looks like it is possible to create gists programmatically as long as you are anonymous:

https://developer.github.com/v3/gists/#create-a-gist

example: https://jsfiddle.net/zcpkfcuu/11/

This should probably be sufficient for a first pass at an "export to gist" function. One big caveat is that you can't *delete* gists made in this way, but I think this should be ok for a first pass. Just being able to quickly export and share gists anonymously via the current client side app would be a huge win.

**Comment by bcolloran** [comment]
Oh cool. This sounds like a nice little thing to try out in a lightweight PR

**Comment by wlach** [comment]
@hereisnaman do you want to give this a try? ^^

**Comment by hereisnaman** [comment]
@wlach I am already done with the backend part for authentication with github. I am working on integrating with the frontend and setup gists.

**Comment by bcolloran** [comment]
we have a version of this working, yay!

**Comment by vadimkantorov** [comment]
Is there an up-to-date way of running a JSMD from a GitHub Gist or a GitHub repo? (public ones to begin with)

It'd be very useful, many people are already quite used to trust their code to GitHub.
