### ISSUE TITLE
ctrl-d should just delete the character under the cursor, not popup declared variables pane

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#392]
Probably based on 20+ years of using emacs, using CTRL-D to delete the current character under the cursor is pretty hard-embedded in my muscle memory. Virtually every text editing environment I use (including Atom and Firefox's default text entry box) also supports it.

I know there's been a bunch of churn on this (#159, #387) which I hate to revert, but this is a huge frustration point whenever I use the environment (sorry for not filing the bug until now). I think we just need to find another shortcut for the "declared variables" pane. For all intents and purposes I think this keybinding is "reserved"-- it's no doubt a minority of people that use it, but those who do (like me) *really* care about it.

**Comment by wlach** [comment]
@bcolloran @hamilton do you have any ideas on this? ideas for an alternate shortcut? :)

**Comment by bcolloran** [comment]
oops, i replied but i hit the wrong button i guess.

i think it's fine to remove ctrl-d -- not an emacs user, so i didn't know it was a pain point. I think we can either find a new shortcut (no particularly strong feelings about what key to use (ctrl-g for "globals" maybe?) so happy to defer on that; or, imo it'd also be fine to skip the kbd shortcut for now, since we currently have a button and will eventually make this available by kbd thru the "command palette"

also, codemirror supports emacs and vim modes in addition to sublime. would it be worth looking into having those available as config options?

**Comment by wlach** [comment]
I'm not sure if I'm going to have time to work on this in the next few days, so unassigning myself in case someone wants to give it a try. Things to do:

1. Revert #159, #387
2. Remove the ctrl-D keybinding for displaying declared variables.
3. Verify that pressing CTRL/COMMAND-D works as expected inside a notebook cell

**Comment by wlach** [comment]
@bcolloran I'm personally fine with the sublime bindings for now, but emacs/vim bindings for sure might be something we would want to offer in the future. I think we might want to leave it for a later milestone though, as I don't know if they're worth the additional churn right now.

**Comment by hamilton** [comment]
Totally fine either changing this or making it so it doesn't fire in edit mode.

**Comment by bcolloran** [comment]
as mentioned in #398 --
it turns out that the default ctrl-d keybinding in sublime text is to select other instances of the word under the cursor. i'm not sure if we should single out ctrl-d as the one exception to the sublime keymap, or maybe just leave it until we can put in keymap selection? (i.e., allow users to select emacs/vim/etc)
