### ISSUE TITLE
External Dependency output handler requires some tweaks

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#400]
Though we are deprecating the `ExternalDependencyCell` soon in favor of a more programmatic approach, I noticed some design quirks of the output handler, which will likely be a part of the iodide stdlib. We have another branch where we can import an emscripten-compiled version of Python (the language) which adds a large number of vars to the global namespace. So the below points are motivated by the following gif:

![feb-23-2018 23-29-48](https://user-images.githubusercontent.com/95735/36627024-862079d2-18f1-11e8-9835-c8555b7ad1ac.gif)

- [ ] If there are more than a handful of objects added, it becomes overwhelming. Perhaps only render 10-12 vars and then provide a (... and x more) which can be clicked to expand to the full list, if wanted.
- [ ] the check should be aligned with the first line, not with the parent middle.

**Comment by mdboom** [comment]
Agree this should be fixed in general, but just an update: the latest version of Pyodide doesn't do this to the namespace.  It was initially using the `asm.js` compilation target, but the `wasm` compilation target doesn't need to have all these global variables around.  I think the latter really assumed you were compiling a standalone application -- `wasm` is better designed around the idea of compiling a library that is then used from vanilla Javascript.

**Comment by hamilton** [comment]
Closing this since we don't use the external dependency type anymore (in favor of `fetch`)
