### ISSUE TITLE
Exporting Iodide notebooks as PDF 

### ISSUE THREAD

**Issue by imshubhamsingh** [iodide-project/iodide#421]
Current there is no good way of exporting iodide notebook to pdf (useful for reports etc.).
> Even converting html to pdf is no good. 
![image](https://user-images.githubusercontent.com/17807743/36899372-cc369782-1e44-11e8-929c-e1ff5922464b.png)

**Converting notebook to pdf is a worthwhile notebook level option.**

We can use jsPDF and html2canvas for it conversion to pdf.

**Comment by hamilton** [comment]
Good idea! Will need some discussion from others.

**Comment by bcolloran** [comment]
Hmm, two cent-- i'm not sure this would be inline with our value proposition, or with our computation model -- I'm most interested in focusing on the use cases which are not well-served by other tools: frictionless sharing of live, interactive, editable, computable documents, not static artifacts. There are a lot of tools that do a great job serving static artifacts already, and I don't think we have any comparative advantage against those tool.

I'm happy to hear more about the need and expected use cases of this functionality, but my prior is that this feature would only justify a very minuscule cost of support (so if it adds basically any complexity or code weight to the app, I'm probably not into it). In any case, even if we do decide we want this, it'd be very low priority -- we have so many things to work on for the interactive use case.

**Comment by hamilton** [comment]
@bcolloran I agree - this is not a high priority for us. One counterargument for not having a documented way of exporting as a pdf, however, is some analysts will find they still need the 'paper' version to do their job at times, and if we don't have an easy way to make this happen, I wonder if some users would avoid this product altogether simply because they can't actually get it to someone in the format the receiver expects or demands. Users won't always know where their analysis will go or how it will need to be consumed in the future. People print out reports and articles all the time for marking up (seems especially true in the academic world), publications may require a pdf, an older coauthor wants to just print it out or read it on his or her computer, or maybe a c-level exec wants a pdf so he or she can just read it on a tablet on the plane, or any number of similar use cases.

W/ that in mind, my 2c: this is not really in scope for 0.4a or 0.5a, and when we feel better about the state of the app I'd imagine this would be fairly easy to lightly format the presentation view via CSS so that you can just export to PDF via the browser's print functionality. That'd be more than enough of a starting point, imo. But I'd vote that we kick this can down the alley for now, since that is still more work than anyone should do right now.

**Comment by bcolloran** [comment]
out of scope for the foreseeable future
