### ISSUE TITLE
onClick prop not getting passed down to cell submenu

### ISSUE THREAD

**Issue by hereisnaman** [iodide-project/iodide#423]
I am able to see a few errors after the commit https://github.com/iodide-project/iodide/commit/1696dc27ceeadabd1a5c9fdf7452bb37119dcb07 .
Mainly in the nav menu and cell section. Many onclick errors and coming and more.
@hamilton can you review that.

![screen shot 2018-03-02 at 5 23 56 pm](https://user-images.githubusercontent.com/22571395/36899126-bb4c5eda-1e43-11e8-86a2-5707728a3f35.png)

![screen shot 2018-03-02 at 8 03 59 pm](https://user-images.githubusercontent.com/22571395/36903839-e1ae6c74-1e54-11e8-8c7a-54f455ad5861.png)

**Comment by hamilton** [comment]
Hmmm - none of these errors surfaced when I was working on this branch nor do they appear on a clean copy of master. Did you happen to run `npm install` again? There are some dependency changes since the merge.

@bcolloran we'll need a better way of telling contributors that a fresh `npm install` is in order, if this is indeed the issue :)

@hereisnaman try that and let me know if the errors persist.

**Comment by hereisnaman** [comment]
@hamilton I did npm install, even tried a new clone of this very repo before submitting the issue.

**Comment by hamilton** [comment]
Yep, tried it on https://iodide-project.github.io/master and found the issue you provided. Something appeared to not be getting properly passed down in the props for the cell menu, which somehow alluded the FF testing. It appears not to be an issue in Chrome. Will file a PR to fix.

The add cell functionality within the menu appears broken due to something in the `scrollToCellIfNeeded` function, and I believe we have an issue open for that.

Thanks for filing.
