### ISSUE TITLE
tighten up notebook header and make sure notebook title gets enough space

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#455]
there a lot of dead space in the header at this point, let's see if we can buy back a few vertical pixels and let's tighten up the horizontal spacing. it looks like the bar is 64px atm; i think somthing like 45-50 would be better proportioned for a desktop experience (my assumption is that the material UI lib uses phone/tablet defaults).

also, note that in the following image, the title text, which should read "Notebook title", is squeezed into a tiny horizontal area, cutting off the start/end of the string. We should make sure that the title text has enough space, and in the process we can tighten up the horizontal spacing around the buttons by a few px to keep the proportions looking good.

![image](https://user-images.githubusercontent.com/2380975/37126642-cafdcb52-2226-11e8-93e0-e45c44a83a10.png)

**Comment by hamilton** [comment]
I'll take this on. It's not quite a bug, since the issue is I ported over our toolbar for my full screen width (which is how I have been using the notebook). There is a "last saved" element to the right of the title which is taking up just a bit too much space, it seems, if you tend to keep windows narrower. One option is to remove it entirely, and the other is to make it smaller. I'm going to opt for the latter for now.

Also, this should be two issues probably, not one, but I can take care of both in the same PR.

**Comment by hamilton** [comment]
I could also remove the "saved 8 minutes ago" in favor of an icon that has a tooltip, which would give maximum space to the title (which I'm all for)

**Comment by bcolloran** [comment]
yea that looks good, but of course it's hard to tell without seeing the window in a narrow view. For now, i think testing down to about 850 or 900px width is what i'd aim for.

ya i thought this was all related and would be better bundled as one issue/pr, but certainly go ahead and break it up if that seems better

**Comment by hamilton** [comment]
No prob - this basically boils down to a responsive design task, shouldn't take long
