### ISSUE TITLE
make matrix reps look nicer (closer to LaTeX)

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#492]
Appropriating this issue to discuss the matrix design.

**Comment by bcolloran** [comment]
i don't think this rises to the urgency of a bug per se, it's a relatively minor thing. and the matrices still look fine, it doesn't break the rendering or anything. :-) so i'll remove that tag from this issue

seem like what we want here is:
a) add a specific class to matrix outputs so that we can give them their own custom style
b) add a nice custom style in our css that renders matrices nicely

this is pretty much how latex renders matrices:
![image](https://user-images.githubusercontent.com/2380975/37549488-c6e2d17a-293d-11e8-969b-eabf46f7294d.png)
or maybe even more often with square brackets:
![image](https://user-images.githubusercontent.com/2380975/37549503-eca5ef3c-293d-11e8-97ad-8fd8be570c5f.png)

someone could try to figure out how to get matrices to render like that :-)

**Comment by bcolloran** [comment]
closed via #1419
