### ISSUE TITLE
syntax highlighting within markdown code blocks

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#496]
I am writing some documentation w/ iodide for a small project I had started a few months ago, and am noticing that (at the moment) it is hard to get nice syntax highlighting in presentation mode automatically. using the GH-flavored markdown approach (putting the language name in triple tick blocks) works in CodeMirror, but the generated html is not syntax highlighted.

It is possible that this will all be side-stepped by "show input in presentation", which would give us a CodeMirror instance w/ all the usual highlighting. imo this would be a much more concise way of integrating code & prose.

All the same, there are probably use-cases where you want to syntax highlight a code block without having that available. Let's say I want to demonstrate a code block in Clojure or something, but not actually write any Clojure code in iodide.

It turns out `markdown-it` has [an easy way to do this](https://markdown-it.github.io/markdown-it/#syntax-highlighting) kind of thing.

With that in mind, I would like to open this up for discussion. Should we be applying syntax highlighting `markdown-it` plugins?

**Comment by bcolloran** [comment]
discussion point from #498 --

i wonder whether we should be building this into our core bundle, or supporting this as an instance of a more generic problem and building it as a plugin. I think that approach is probably right in the long run -- allow users to add markdown extensions at runtime (this, TOC, etc) so that (a) we don't have to build everything into core Iodide (to keep the bundle slim), and (b) users can be empowered to add little thingies that extend the makrdown parser functionality for all of their weird little niche use cases.

**Comment by hamilton** [comment]
Closing this since we believe this should be supported as a plugin, not part of iodide.
