### ISSUE TITLE
arrays of arrays of objects breaks the output handler

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#516]
I encountered this while doing some actual internal work with iodide.

Arrays of arrays of objects causes an error in the output handler.

Non-objects do not seem to break the output handler. For instance, arrays of arrays of strings, or arrays of arrays of numbers don't break the handler.

## steps to reproduce

1. [open this notebook](https://iodide-project.github.io/master/?url=https://gist.githubusercontent.com/hamilton/2ba3e19c2ab21a184ca5111b839226ae/raw/d743c96eb4c6962892d748987732b37fab232f0b/array-of-arrays-of-objects-breaks.html) 
2. run all cells

## what I expected

An array of objects in some capacity, either through JSON tree viewer, or just `object` as a string

## what happened

Take a look at the console to see the React error. This error also keeps the app from doing anything else which forces a reload, so perhaps we should have a try-catch statement when putting data through the output handlers.

**Comment by imshubhamsingh** [comment]
@hamilton I've fixed this issue, just before rendering it is checking for an object. If it is there it'll render a json.
![fix](https://user-images.githubusercontent.com/17807743/38001139-cc979696-3248-11e8-8489-e0c6f0e4fce6.gif)

**Comment by imshubhamsingh** [comment]
Just did a [PR](https://github.com/iodide-project/iodide/pull/522)

**Comment by bcolloran** [comment]
Hi @imshubhamsingh, thanks for looking into this issue. I believe the behavior we want is similar to what is implemented for the data table output. That is: we want arrays of arrays to recursively call the output handlers on the contents of each matrix cell, rather than replacing the matrix style presentation altogether. @hamilton is that correct?

**Comment by imshubhamsingh** [comment]
@bcolloran @hamilton how should I handle if an object has keys. I tried this: 
![image](https://user-images.githubusercontent.com/17807743/38061682-e63c56ca-330d-11e8-9d05-fb95cce1f757.png)

**Comment by hamilton** [comment]
@imshubhamsingh I think for now we can just use `.toString()` on any object in the array of arrays. Down the line we will have a better representation for recursively calling output handlers to support a short, medium, and long representation of objects. For now it would be enough that a user sees `myObj.toString()` or whatever.

**Comment by hamilton** [comment]
@djbarnwal is this something you'd like to take on / is it related to what you brought up during the team meeting?

**Comment by djbarnwal** [comment]
@hamilton The issue I brought up at the team meeting was quite different but along the lines of output handling. Suppose we create a DOM element using the markdown cell in our notebook and say we use D3 to add a bar plot to that DOM element. Now as a user, I would like to fine-tune my bar plot by changing some pieces of the code. Re-running the updated cell would add another bar plot to the DOM element. What I would ideally want is only one bar plot or some mechanism to handle and clear output of the DOM element. For now, in order to achieve this, I have to reload the notebook from the cell menu or change the DOM's ID at both the places. I am not sure if this issue reflects the interest of other users too but it has been bugging me for quite some time.

**Comment by bcolloran** [comment]
@djbarnwal this use case should also be served by `iodide.DOM.element` stdlib function that we're experimenting with over at #587

**Comment by bcolloran** [comment]
@djbarnwal would creating DOM elements like this meet your needs?--
https://iodide-project.github.io/master/?gist=bcolloran/f16031ce759642cbd2f2b56b752bab87

**Comment by djbarnwal** [comment]
@bcolloran Yes looks great, this is exactly what I was looking for.

**Comment by bcolloran** [comment]
on iframe-2 this doesn't cause an error, but one is shown an array of data tables (at least if all the objects have the same keys), which is also not great

**Comment by hamilton** [comment]
This is fixed in master, so I'm going to close it. _how_ it is displayed can be addressed in a future issue.
