### ISSUE TITLE
proposals re: freezing environment variables

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#551]
Objective: to enable users to "freeze" some user-defined variables from their global js execution scope so that expensive computations can skipped when sharing notebooks.

#### writing and export
- During exploration phase, a user runs a bunch of cells, including some slow computations.
- As the narrative that the user wants to tell begins to crystallize, the user realizes that only some of the outputs from these computations will be needed to create their final report.
- the user marks the cells with expensive computations as "skip in run all"
- The user creates an "environment cell" that includes the names of several variables from the global scope.
- Upon running this cell, the indicated variables are saved _in their current form_ to the iodide store
    - running it multiple time will allow updating of the frozen environment vars
- At export, the frozen env variables are added to the JSMD

#### reading and import
- At next import, the saved env vars are immediately dropped into the global namespace (before the "run all" action is triggered).
- since the author marked a bunch of cells as "skip", the non-skipped cells will begin running right away with access to the frozen values of the intermediate computations.
- the user immediately see the report the author intended

#### server-side execution
- for the server-side computation we've been thinking of, the default might be to ignore "skip in run all", or to have a flag that allows this.
- this would mean that the server-side runner would execute the NB cells in order, attach the specified  vars to the iodide store when it hits the env cell, keep executing the NB until the end (including any additional env cells) and at the end the server-side runner script would emit a new notebook with jsmd that includes the frozen values of these variable
- then when a user loads the NB in the browser in Report view, the env vars will be loaded immediately and the "skips" will be honored, dropping the reader right into the report as the author intends

#### wrinkles
- i need to look more for a good library that can "pickle" objects, but it may be the case that serializing functions (and hence js classes / class instances?) is not a straightforward thing to do, so we might need to forbid that. in that case, we'd want to throw obvious errors in the UI.

**Comment by bcolloran** [comment]
hmm, thinking about this more: maybe this should actually be a iodide lib call rather than a new cell type? and perhaps the author should also have to explicitly unpack and process the stored env vars

something like:
- `iodide.freezeEnvironment(objWithVarsToFreeze <object>)` that takes an object like `{x: <simple type>, ... , z: <simple type>}`, and stuffs that object into `state.environment` (which gets serialized at export).
    - Here `<simple type>` are types that have easy representations (string, bool, number)
- `iodide.thawEnvironment()` returns an object containing the serialized strings in the environment.

By analogy: you don't normally need to serialize a whole pandas object, just the data inside of it, and ou use the functionality built into

example workflow in JSMD:
``` javascript
%% js {"skip":true}
// expensive computation

%% js {"skip":true}
// expensive computation

%% js {"skip":true}
// expensive computation

%% js {"skip":true}
iodide.freezeEnvironment({
  corrMatrix: JSON.stringify(M),
  dataSample: myDataFrame.serialize(),
  quadrillionthDigitOfPi: digitOfPi, // number
})

%% js
{ corrMatrix, dataSample, quadrillionthDigitOfPi } = iodide.thawEnvironment()
corrMatrix = JSON.parse(corrMatrix)
dataSample = dataFrameLibrary.read(dataSample)
// quadrillionthDigitOfPi doesn't need to be unpacked, b/c numbers can be saved without needing serialization

%% js
// visualization or whatevs
```

so in the above workflow, what happens is:
- the author has run a bunch of code, figured out the variables they need for the rest of their story, and explicitly frozen those variables in the environment.
- then they marked all the cells above and including the cell with `freezeEnvironment` as "skip", so that (a) the expensive computations will be skipped during run all (including in the case of the run all when an NB is loaded in Report view); and (b) run all in report view will explicitly reload the env vars needed for the story.

#### cons
- less magical than doing all the serialization automagically
    - user needs to handle stringifying/parsing
#### pros
- less magical than doing all the serialization automagically
    - explicit rather than implicit
    - don't dump globals at NB start
- iodide doesn't need to know how to serialize every kind of thing in the universe, so we don't have to build that all right now (faster path to MVP)
- doesn't add another cell type to keep track of (less complexity in code, in state, in UI, in keybindings...)
- you can choose to re-run `iodide.thawEnv()` to reset your NB and test that it works as you wish from wherever you last left off.
#### unclear if pro or con
- not clear whether the additional cell type makes the mental model of the workflow easier or harder to understand



i think i'm favoring this approach somewhat to adding _another_ cell type.

**Comment by bcolloran** [comment]
i'm going to try starting the stdlib approach. much of the code/learning should be reusable even if we decide to go with a cell type later.

**Comment by bcolloran** [comment]
@hamilton @mdboom thoughts?

**Comment by hamilton** [comment]
Hmm.

I agree that a new cell is not the approach we would want to take. This is more of a stdlib call, or an option when exporting a notebook. The explicitness of stdlib call is pretty good. Being able to also programmatically freeze (or thaw) the state could lead to a ton of different interesting use-cases.

It would be good to walk through a few use cases. To start, I can see a ton of cases where a user has frozen the state of something and are intently continuing work with the frozen version of their data, then realize they need to not freeze the state of that thing because the underlying data may have changed in a way that means they don't need to freeze or they got something wrong, so they'll need to re-save the notebook without the frozen state. What is our "undo frozen state" story?

One aspect of a stdlib approach that I think is perhaps a con is: by doing all of this programmatically, it forces us to consider dealing with the overall notebook state within the cell paradigm, and not within the saving / notebook paradigm (for better or for worse). I thought the solution to this originally would be to have this either be an export-side feature, or something that is done in the declared variables pane ("serialize this and load it" kind of button). That way we can handle the case of unfreezing / removing frozen variables if that was indeed the wrong choice at some juncture without hurting the user.

The _downside_ of having this be a notebook-level (vs. programmatic) approach is obviously we lose all the benefits of programmatic serialization, which are numerous.

It could be that the solution may be to have some additional means of inspecting what is frozen, and what will be frozen, and taking actions on those pieces of state, all outside of the explicit cell paradigm.

I'm very curious to hear what @mdboom thinks. He's done a lot of thinking about snapshot / freeze state issues in Jupyter.

**Comment by mdboom** [comment]
Interesting discussion.  Indeed, these are the kinds of things that I hear people wanting to solve in Jupyter as well, and I don't think the problems and solutions are all that different between Iodide and Jupyter in this case.

I like the idea of starting with a programmatic approach and possibly laying "UI sugar" on top of it after.  It will be faster to iterate and explore this that way.

For the set of freezable data types, I think you have to limit it to the JSON types -- any thing else gets weird really fast.  I think when you freeze something that's not obvious JSON, we have a big message that says "Can't freeze this, because you put a {type X} thing in there."

My thinking on this so far has been a little different in that it's tied closer to cells.  For any cell, you can set it to "running" or "frozen" mode.  When you want to freeze, you tell it which variables to freeze.  Programmatically in Python, this looks like:

```
with frozen(['x', 'y', 'z']):
    # ... do some long running thing ...
```

In Javascript, you'd probably do:

```
frozen(['x', 'y', 'z'], () => { // ... long running calculation... })
```

The frozen method has a way of getting the frozen state of the cell (hand wavy now, but should be possible).  If not frozen, it runs the code, and then places the requested variables in storage.  If frozen, it just pulls them out of storage without running the code.

One could imagine UI on top of this that removes the need for the syntax, and would let you select the variables to freeze from a list of newly added or modified variables from running the cell's code.

**pros:** 

It keeps the cell as the sort of atomic unit of work, and doesn't create dependencies between cells that do work and those that perform caching/uncaching.

Caching/uncaching happen through the same function, using a cell-level attribute to determine how to behave.  (So there's no separate caching/uncaching code to keep in sync).

**cons:**

It's certainly less flexible that what's described above, particularly if the long running computation spans multiple cells.  We may need a grouping of cells to really make this make sense, which is complexity.

But in summary, I think this is one of those tricky problems that we need to build and play with.
