### ISSUE TITLE
If I return a DOM element, it should render a DOM-inspector in the output

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#572]
Will be addressed by #571.

**Comment by hamilton** [comment]
This is definitely not what we want to do. Here's an example why:

![apr-17-2018 22-48-27](https://user-images.githubusercontent.com/95735/38942510-d832a9ae-42e3-11e8-85a6-c143b1708732.gif)

**Comment by bcolloran** [comment]
i think using the dom inspector is ok, but i don't know that the example presented is entirely convincing. obvi users can do all kinds of stupid stuff if they want -- `document.getElementById('page').innerHTML=""` -- so i wonder if there are other reasons why we wouldn't want to render DOM elements? In general, doing so seem like it would be the expected behavior (and that having the inspector available as a secondary view is desirable). But i haven't thought about other bad outcomes at all. Anyhoo, let's reopen this as a place for further discussion/feedback. (but let's just go with the inspector in the meantime)

**Comment by hamilton** [comment]
After some discussion, we're good w/ going through with the raw DOM element for now. This will be fixed with #571.

**Comment by hamilton** [comment]
Closing this now that #571 has been merged.
