### ISSUE TITLE
[META] iodide webextension design discussion

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#590]
@djbarnwal @hamilton @wlach @mdboom --

Let's use this issue to discuss ideas about what web extension for Iodide could do, and how we might implement that extension (including discussion of security implications).

For background, please review https://github.com/iodide-project/iodide/issues/361

To outline what I think are the high-level objectives we would want to achieve:
- we want to enhance client-side file-based workflows and to allow Iodide notebooks to fit into people's into existing workflows, since many users have long-standing file-oriented workflows around juptyer notebooks
    - Perhaps most importantly, github (initially) integration is most important -- we want to. (This is complementary to the Iodide server @wlach is building, which will enable online workflows)
    - Functionality that streamlines saving files to the filesystem would certainly be in scope for this. our options may be limited because the `downloads` api gives you very little control of where you can save files, but there might be a few things we can do. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download

**Comment by bcolloran** [comment]
One other workflow enhancement that might would be helpful for the core devs would be something that makes it easy to move between local notebooks that point at `dev/iodide.dev.*` and hosted resources

**Comment by djbarnwal** [comment]
It is quite evident that we need a better mechanism for saving and sharing Iodide notebooks. Iodide web extension can be of huge help here. Once we have a user's authorization, we can develop a plethora of features such as - pushing the notebook as a repository, deploying a notebook as a GitHub page, deploying as gists with a shareable link and much more.

We can also use the web extension for add-ons such as Themes and Templates for Iodide notebooks.

Web extensions work with js and CSS files and do not interact with HTML files directly. So to create DOM elements, one has to use JS. Using React will help us with the above case along with bringing all the other good things it has to offer.

For authorization, Auth0 can be used. Auth0 has an option to make an account without any limits for Open Source projects. Using Auth0 would help us with our backend problems and allow us to scale without any issue.

**Comment by hamilton** [comment]
This sounds great. I'm concerned that the real value add will be the server for our users, not the web extension. A server will be more familiar and has wider implications for usage.

Given that you can accomplish some of the same general goals (auth, saving notebooks, etc.), and given that a frontend component for this will effectively be another react single page application to handle these additional features (possibly?), perhaps it is worth thinking about the general goals for both projects and aiming to make _one_ frontend that accomplishes the goals for both, so we we are not duplicating work with our limited resources.

In which case, I think it would be good keying @wlach into this conversation since the server may be in harmony with some of the tasks.

Curious to get everyone else's thought on the parallels. Some thinking about what is shared between the server & web extension:

- saving to filesystem and auth may need to be hooked into an individual notebook for keybindings, in-notebook UI changes, etc.
- auth is going to require a few additional views, perhaps only as modal that sits ontop of the current page. Listing where you are auth'd, what the username is for the auth'd account, option to log off of that auth, etc. is all going to be valuable information for a user. Is this something we plan on just putting together for the IDE, or should it be entirely server/webextension-side in some way?
- a simple view for seeing all of one's saved notebooks, renaming, deleting, etc. 
- some additional mechanism to say if a notebook is / isn't connected to a webextension / server as a way of suggesting the saving functionality is limited.

**Comment by wlach** [comment]
As I've said in meetings before, I am personally kind of uncomfortable with the idea of an iodide extension -- it feels to me a bit like doing an "end run" around cross origin restrictions in browsers and websites that are there for a reason. The implications of someone exploiting a vulnerability in our extension and gaining access to someone's github account seem scary to me. And I don't really see any use cases there that couldn't be accomplished by a server that is redeployable in the cloud.

I get how being able to save iodide notebooks to the filesystem, etc. was useful for development, but I  feel like the way forward is to make it as easy as possible for people to deploy their own server side solutions. The neat thing about iodide is that the computational requirements of such a thing are *much* lower than they would be in the case of something like jupyter, since most of the workload is handled by the client.

That said, if people really want to do things this way, we could probably come up with a design that accommodated both approaches.

FWIW, my current prototype of a redeployable server with github login is here:

https://github.com/wlach/iodide/tree/iodide-server

This "works" in the sense that there are some simple views which support login, as well as serving of a  static copy of iodide. The next step is to hook the login workflow into the static assets (i.e. adding a login button to the frontend). Was hoping to be able to do this last week, but ran out of time. If anyone wants to help collaborate on this, they would be more than welcome.

I think auth0 would be a great logical next step after we got github working nicely (it would be perfect for mozilla's use case).

**Comment by bcolloran** [comment]
one note from a discussion that @wlach @hamilton and I had a moment ago is that we can accomplish quite similar functionality with a localhost server that can write to the file system and talk to github and/or other online services. we still have more thinking to do on this topic, but that's another possible avenue

**Comment by hamilton** [comment]
@bcolloran should we say this is `wontfix` for now & close it?

**Comment by bcolloran** [comment]
yea WFM. My best guess at this point is that the future is:
- electron app
- lightweight "open notebook in electron app" extension
