### ISSUE TITLE
iodide.output.text does not target the side effect row properly

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#596]
[This example](https://iodide-project.github.io/master/?gist=hamilton/d30073525f36e084a6d5e34c7b8c366f) demonstrates the issue. The call to `iodide.output.text` may only be targeting the currently-selected cell, when it should target the cell in which it was called.

I would expect the code example to continue to output `eyy! ${c}` but I am not sure it knows where to output.

**Comment by bcolloran** [comment]
interesting. that example is quite subtle. For an example like that, in which `iodide.output.text` will be called after some delay, and after the cell evaluation has completed ("completed" in the sense that `store.getState().runningCellID` will not point to the current cell (and may indeed not point to any cell)), it seems that there is no way for the `iodide.output.text` call to know which cell it was called from -- the `iodide.output.text` call can happen at an arbitrary time, and there is no way to "mark" the function call as belonging to a cell at the cell time.

the only work around i could think of -- and I really quite despise this idea, it seems very ugly -- would be to inject the cell number into each evaluation by appending it to the top of the code to be evaled. that is, instead of `eval(code)`, it would be

``` javascript
eval(`const __IODIDE_CELL_NUMBER = ${cellNumber}
${code}`)
```

my thinking was that  `__IODIDE_CELL_NUMBER` might be available in the eval scope when `iodide.output.text` is called, and the DOM manipulations could be made to target the correct cell by looking for  `__IODIDE_CELL_NUMBER` rather than `store.getState().runningCellID`

i experimented with this for a while and could not get it to work -- i misunderstood the scoping. a `const` defined at the top of an eval is not visible to the internals of `iodide.output.text`, so this won't work.

I think this may be actually not possible to fix, given the set of constraints re eval, scoping, and timing factors that come into play on this one.

in that case, the solution will have to be documentation -- we can say that `iodide.output.text` is provided as a convenience function, and that it is not guaranteed to work in all contexts; that in particular, it may not work correctly when run inside of an async context, and that we advise that calls to `iodide.output.text` and `iodide.output.element` be called syncronously at the top level of a cell.

for the example you gave, the workaround for the user would be would be:

```
textTarget = iodide.output.element("div")
let c = 0
setTimeout(()=>{
 textTarget.innerHTML = `eyyy! ${c}`
  c+=1
},4000)
```

**Comment by hamilton** [comment]
hmm ... I think we can figure out a solution that works, and keep this issue open until we have a better plan. If we can't figure it out, we should find someone who can and have them advise on this issue.

If this feels like it's intractable in its current form, perhaps we could have `iodide.output.text()` return a function that closes over the cell ID, so every call to that resulting function does what we want in the place where we want it. It'd look something like this:

```javascript

let print = iodide.output.text()
setTimeout(()=>{
  print(`eyyy!`)
}, 4000)
```

This isn't really that ugly, I think, but ymmv.

**Comment by bcolloran** [comment]
possibility: at the top of each eval, deep copy `iodide` from global scope to cell scope and inject the cell id into the `iodide` object.

**Comment by bcolloran** [comment]
related to #587
