### ISSUE TITLE
promise rep tweaks

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#607]
a few thoughts on the promise rep:

- i don't think the rep should automatically show the value when the promise resolves. See e.g.:
https://iodide-project.github.io/master/?gist=bcolloran/2e104b3fc28f68454a23626e11bc8678
    - in cases like this where the value is a data set, and in particular, a text string (which will not be uncommon for handling data sets) it can end up outputting a ton of content, and not really the content you want to see
    - because promises may resolve later, it can make the UI bounce if you're at a cell below when the promise resolves
- just as is the case in the devtools pane, we want to highlight the fact that the user is getting back a Promise object; the way it's rendered now, it's not clear that the value "belongs" to the promise

I'd propose that for now, we just show the promise badge thingy, but that in the longer-term, we include a button on the promise badge thingy that appear when the promise resolves/rejects that let's you expand the value ; and furthermore, the value should be shown in some kind of box to indicate that it belongs to the promise

**Comment by hamilton** [comment]
Interesting!

1.) I think that example is really surfacing a problem in the rep for the gigantic string, not the promise. If I were to synchronously load a data set, the rep would still be broken there.
2.) From a conceptual point of view, a Promise is a deferred value, so showing the value of the promise once it is resolved / rejected (for instance, returning an error) does give a lot of immediate power to the promise, and is in-line with what a Promise is all about - a deferred value. Perhaps one approach is to add an additional label that says something like `deferred value:` so that it is clear that indeed this promise has returned something or other. I'd also be happy to hide it in some way, but having the Promise value has been very useful to me, even if the rep it is using for the deferred value is broken.

Happy to talk about this more and think further on the issue, but I can say that being able to view a data table once my Promise loads has been a really nice UX experience, and I want to make sure that the problems inherent with the Promise rep are specifically about the Promise rep itself and not some other rep.

**Comment by bcolloran** [comment]
re (1) good point
re (2) a promise more than just a deferred value, it is a distinct object that needs to be handled as a promise, so the UI needs to be very clear that the value returned by the cell is a promise object, and that the promise objet's value belongs to the promise object. I'd favor following the devtool reps on this, but minimally, the promise rep should wrap it's value in a box or somthing to indicate that the value belongs to the promise

**Comment by bcolloran** [comment]
closed via #1419
