### ISSUE TITLE
how to handle UI changes due to server-side component(s)

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#615]
The frontend for iodide will over time get augmented, with new menu items, keybindings, and functionality. We will need a way to hook into the frontend to apply new functionality and plugins down the line.

There are two options as I see it:

- if I'm loading a notebook purely client-side (without any kind of "hosted" backend - webextension, server, electron app, etc.), perhaps we should gray out any functionality that doesn't exist, but otherwise show the full host of default iodide functions. I think this is kind of limited, since 1) it would tie the notion of the notebook to a server of some kind, and 2) it doesn't account for any expansion or plugins.
- come up with a small ui-adding plugin architecture, so if my server component adds some new buttons or adds a special login, the app itself knows how to interface with that and accordingly adds, without the server component needing to import a special component or whatever. 

@mdboom do you have a sense of how jupyter handles this? I know you're working on some plugins that extend functionality.

**Comment by mdboom** [comment]
Jupyter doesn't handle this very well (extensions basically just hack the DOM of the UI and hope that nothing changed between versions), however JupyterLab handles this pretty well.  There's a concept of "actions" which all get added to a generic "action palette" (like many editors have), but then extensions can also add toolbar buttons, hot keys, menu items that trigger these actions anywhere you like.  I think just having API functions to add these things dynamically from the notebook content itself or JS loaded through an external resource cell would probably be sufficient.

**Comment by mdboom** [comment]
Just clued in that this also says "server-side".  Jupyter has both server and frontend extensions, and they are basically independent (they might get installed together from the same PyPI package, but they still are registered and enabled independently).  So if you have a server extension, it will need to have its front end installed or the server side thing will basically have no UI.  I'm not sure that's a great situation -- it's kind of easy to have the two fall out of sync.  JupyterLab makes it even more brittle, IMHO, since the Javascript side now *must* be installed through npm so both the installation and registration steps are now completely independent.

One way that I think might be better is that our server would have a standard endpoint to get Javascript that should be loaded into the frontend to add the UI elements.  That could be essentially static, or if the server grows a plugin architecture, it could wrap up the javascript from all of its plugins and serve the whole thing together.  And if there's no server, that stuff never gets run and the UI isn't changed.  Though it would probably be good to indicate to the user which "mode" (serverless or server-backed) they are currently in.

**Comment by bcolloran** [comment]
@hamilton let's talk about this in person. in the near term, i think we only want to worry about the "official" iodide-server
