### ISSUE TITLE
More fully featured iodide server MVP

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#633]
As discussed in the iodide meeting, I think we should flesh out the existing heroku server with some api endpoints that allow saving notebooks to a database.

I've been fleshing out a rough specification of what this might look like here:

https://docs.google.com/document/d/14IXKI_TRwBJbYDDC1Za_6rHowfGBgPuaLGmsopYGDd8/edit

This is a very early draft that I put together in a short period of time. I still need to add some thoughts on how these API will link up to the UI. Please feel free to add comments/feedback

People who might work on this: @wlach (me, wrote initial heroku server) @djbarnwal (extended initial proposal to support exporting to gist) @cnwangjie (contributor to metricsgraphics, interested in working on some more server side code)

References:
* Initial implementation: https://github.com/iodide-project/iodide/blob/master/index.js
* @djbarnwal's PR to add gist support: https://github.com/iodide-project/iodide/pull/620

**Comment by mdboom** [comment]
Looks good as an MVP.
I feel like **basic** revision support (like Dropbox, not like Github) would be really powerful in this context.  I don't know if we need to contemplate that now or not -- it would probably require a different database schema to support it at a minimum.

**Comment by hamilton** [comment]
@wlach this is great! I'm inclined to agree with @mdboom re: basic revision support. This seems like it's probably worth having in-place, perhaps not mvp, but definitely soon after. But this could simply be another table that keys against the notebook table, I'm thinking.

**Comment by bcolloran** [comment]
@wlach @djbarnwal -- i'm behind whatever approach you guys want to take to get up and running. of course @mdboom and @hamilton are right that we'll want more features in the future, but if you prefer to start with small chunks and add features as we go rather than boiling the ocean all at once, that works for me.

i think that for now its fine to iterate fast and break stuff if we have, but to the extent we do want to think ahead about schemas, etc, and to get us on the same page about the workflows we want to support, here are roughly the things that i think we'll want from the server, in rough priority order (see #592 for more on this)

* Allow authenticated users to create notebooks and update existing notebooks
* Allow anyone to list the notebooks associated with a particular user
* List all notebooks in the system
* Basic versioning (dropbox not github)
* Autosave to server (keep a few backup versions)
* Allow users to "fork" notebooks from other users (make a copy of another user's work under their own user account)
* Allow users to submit "PRs" / change requests against a notebook they have forked

again: _I am specifically **not** requesting that you deal with all this right now_ or that you build extra stuff to prepare for a future that may change -- just putting it out there again in case it is helpful to have some of this stuff in the back of your mind. I fully support the mvp plan you have described, and we can build off that as we go.

**Comment by djbarnwal** [comment]
@wlach @bcolloran How are we planning to hook these APIs with the UI. I feel that we are already stuffing a lot inside that one menu button which subsequently opens menus and submenus. As we progress with the project we would be adding more and more features and options. Instead of populating the menu button, we can maybe create a full-width menu bar (like Jupyter). As an alternative, we can also have an off-canvas sidebar (something like [this](https://tympanus.net/Development/OffCanvasMenuEffects/sideslide.html))

**Comment by bcolloran** [comment]
@djbarnwal -- recapping what i recall from the meeting:
(1) for the basic "notebook" level action (saving a notebook, viewing revision of a notebook that is being edited, etc), we want a menu of some kind "within" the notebook. this could be an overlay, a sidebar, a drop down, etc
(2) for "file management" type actions (viewing all notebooks belonging to a user, viewing NBs belonging to other users, viewing trending NBs, etc) we want another view entirely. i guess this view could also host user-level actions (user prefs rather than NB prefs)

@hamilton @wlach do you guys recall anything else about this conversation?

**Comment by bcolloran** [comment]
also, fwiw -- i'm ok moving fast on the functionality first, then playing catch up with the UI as we figure things out. Or, to say it another way:
it is better
(a) to have the UI and the menus be overstuffed and cluttered for a little while if it means we have good saving/sharing/etc workflows sooner; than
(b) to wait on an optimal UI concept but also have to wait on the workflows

so in the short term, please feel free to forge ahead with the backend and feel free to just put the UI elements into the existing locations -- we can clean up the dropdown and header bar later.

**Comment by wlach** [comment]
I don't think this meta-issue is relevant at this stage.
