### ISSUE TITLE
iodide api not in declared variables until you evaluate a cell

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#640]
This is one thing that was brought up by @DevinBayly #638. I would think we want that to be clearly available / inspectable to users, especially new users.

**Comment by quinhill** [comment]
Hello Iodide, 
my two colleagues and I are first-time contributors and looking for a suitable issue to get our feet wet. We noticed that this issue was put on your docket and removed and it currently is not assigned to anyone. Would this be a suitable issue for us to start on, or are there other issues that would be more suitable?
Thank you!

**Comment by bcolloran** [comment]
Sure, this issue and most of the others marked as "tiny" ( https://github.com/iodide-project/iodide/labels/s01%3A%20tiny ) or "good first issue" https://github.com/iodide-project/iodide/issues?q=is%3Aopen+label%3A%22good+first+issue%22 are probably goo places to start. Thanks!

**Comment by hamilton** [comment]
The issue is pretty straightforward. `UPDATE_EVAL_FRAME_FROM_INITIAL_JSMD` assigns into a `newNotebook()` whatever cells & other pieces of state need to be initialized. This happens only when there is non-empty jsmd (so a fresh notebook doesn't have this issue).

I'll have a PR that addresses this in a moment.

**Comment by hamilton** [comment]
Thank for bringing this issue up @DevinBayly! Better late than never on this fix.
