### ISSUE TITLE
add stdlib features for easy data import

### ISSUE THREAD

**Issue by jaredkerim** [iodide-project/iodide#653]
I can imagine it being a very common use case to load JSON from a remote URL and attaching it to a local variable name, right now there's a little recipe for doing that with fetch but it would be nice if there was just a remote data cell type.

**Comment by bcolloran** [comment]
thanks for filing this jared, it raises some interesting questions. i think that in general there are some advantages to keeping things as close to standard code as possible (so e.g. we're actually going to deprecate the external resource cell in favor of a call from the `iodide` stdlib see #288). that said, we want to make it easy to find/do some standard operations.

Mathematica actually has some UX that we could take inspiration from -- as you're writing a Mathematica notebook, it will suggest cell templates and, if you select one, prepopulate and insert them into your NB. so rather than having to go look in another notebook for recipes to e.g. load data, build a plot, load an external script, etc, we could have some kind of UI that lets you insert cells containing recipes for these most commonly performed tasks. This would (a) make it easy for new users to learn to do important workflow tasks (and help people learn JS); while also (b) keeping the NB as close as possible to standard code and preventing a proliferation of cell types

@hamilton @mdboom any thoughts?

**Comment by hamilton** [comment]
Yep @bcolloran I think your read on this feels right to me. We've always thought that having rich runnable documentation (including recipes) would be immensely useful for new users (heck, I'd prefer to use a template every time I do something like this!). Mathematica does a great job of this, and so does Cycling 76's Max. You create objects in Max, right click, pull up the documentation, and you get copy-pasteable examples. I use that about 80% of the time since it is faster than doing the work myself.

It also occurs to me, from @jaredkerim's GH issues, that we haven't reeeeally anticipated the reverse direction of usability. A lot of JS devs have never used a jupyter-style notebook environment, so the onus is on us to improve that uneven jupyter UX experience to something closer to what they're used to. Everyone benefits from that, including scientists.

**Comment by bcolloran** [comment]
+1 great point about "reverse direction usability"

**Comment by bcolloran** [comment]
superseded by #1009
