### ISSUE TITLE
extremely-alpha.iodide.io does not support https

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#674]
Apparently you need to upgrade to some kind of paid heroku plan to make this happen. We should probably do this sooner than later, as plain old http is pretty insecure.

**Comment by bcolloran** [comment]
@wlach what's the cost of a plan that would support our current team and other needs? can we just get something for the whole team, or is this like a per-seat kind of thing?

i'm all in support of upgrading ASAP if it will be advantageous for us. 

i guess the other option might be to look into mozilla hosting of our heroku app. i know we had wanted to avoid dealing with ops for the time being to maintain control/flexibility/speed; but since we'll have to figure out deploying behind LDAP at some point anyway, maybe it'd be worth seeing what the internal options are? (just throwing this out there -- i'm happy to go with the external service if that seems easier and better for where we are)

**Comment by bcolloran** [comment]
ok, sounds good :-)

**Comment by bcolloran** [comment]
@wlach -- i'm now able to get http://extremely-alpha.iodide.io/ to load, an the eval frame loads at https://extremely-alpha.iodide.app/iodide.eval-frame.dev.html (tho as expected, it doesn't do anything when loaded as a standalone page), but loading  http://extremely-alpha.iodide.io/ gives the console message:

`Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://extremely-alpha.iodide.io’) does not match the recipient window’s origin (‘http://extremely-alpha.iodide.io’).`

So we could just change the expected origin to plain http, but it seems better to pull the trigger on the if that will get us SSL upgrade.

quick links to the mozilla heroku mana pages if we want to go that way:
https://mana.mozilla.org/wiki/display/TS/Heroku
https://mana.mozilla.org/wiki/display/WebOps/Heroku

but if that seems like it'll end up being a lot of overhead, we can just upgrade the existing account. i'm happy to do it if you'd like

**Comment by bcolloran** [comment]
upgraded to hobby, https working
