### ISSUE TITLE
iframe2: remove little buttons that show/hide/toggle the eval-frame

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#725]
these have been the source of some confusion in people's dogfooding notes. let's cut these.

**Comment by teonbrooks** [comment]
with the buttons, the hide editor is kind of like the Report view button with the exception that the console/history pane doesn't go away.

the evaluation frame button doesn't do what is expected, it only resizes the pane versus hide it. The expected behavior I thought was that the evaluation frame disappears and the console panel goes full vertical similar to when you close the console panel.

if you decide to keep the buttons, they should be grouped with the history/app message/declared vars buttons for continuity

**Comment by bcolloran** [comment]
@teonbrooks these have been removed in the latest push to `iframe-2`
