### ISSUE TITLE
iframe2: server tweaks

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#740]
@wlach @djbarnwal:
i just pushed a couple tweaks to allow the django server to serve the iframe assets in the iframe-2 branch. poking around a bit, i noticed a couple small things i thought i'd mention for discussion 

- currently, webpack fills in a JS template string to create the root html file, and that template strings is also saved within the app JS bundle so that it can be used to create a functioning html file when a user exports. I think that at least for now, we still want to enable the ability to export a runnable html file that a user can host at their own website. In that case, perhaps we can come up with a way to avoid having multiple copies of the html template for the python and js code. i'm not sure how to accomplish this off-hand, b/c i'm not sure what if any template string formats will work well with JS and python. but LMK if you have ideas
    - _as a short term quick fix_, we can just bring the python htmle template up-to-date with the iframe-2 template at src/html-template.js (which now includes the iframe directly in the html to improve page load times).

- our original plan (which we haven't yet implemented, but still seems like a good idea) was to use the asset naming convention `${IODIDE_FILE}.${VERSION}.${FILE_TYPE}` -- e.g. `iodide.0.3.js` or `iodide.eval-frame.1.5.css` -- tho for the last few months we've just been using e.g. `iodide.dev.js`, `iodide.master.js` etc while we get our versioning story in place. i'm open to other schemes, but i suspect we will want to host the static assets (js, css, iframe html) for old versions of notebooks that are exported, so in instances like `server/templates/base.html`, rather than using hard-coded asset names like `iodide.iodide-server.css`, we may want to move towards using asset string templates `iodide.iodide-server.css`. Happy to consider other approaches (and even open to discussing whether we still want to support this workflow, tho my prior is that we do).

**Comment by wlach** [comment]
Yeah, the duplication between python and webpack is not great. Using Django's templating system to prepopulate the notebook with the appropriate content is pretty nice, since it cuts down on loading time a bunch. There is almost certainly a way of getting similar behavior while just using the webpack assets though (maybe by autogenerating the template from them at runtime?).

For the versioning story, I'd prefer to solve that as its own issue as we evolve the server to support various use cases (like e.g. making a notebook available at another location).

**Comment by bcolloran** [comment]
i'm going to migrate this to a few distinct issues
