### ISSUE TITLE
remove "external link task" 

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#767]
all instances of "external link task" just open plain urls. For this simple use case, let's prefer to just use plain JSX rather than the extra layers of indirection and complexity involved in this composed class. this falls under yagni and kiss

**Comment by hamilton** [comment]
FYI I think "yagni" and "kiss" are actually not applicable here. Material ui menus don't play nicely with `<a>` tags, otherwise we would have used jsx from the outset. Links break the delicate css that appears to exist with material ui. That may have been fixed when we migrated to the new version, but there was a clear need for `ExternalLinkTask` from the get go because of the library's opinionated approach.

**Comment by bcolloran** [comment]
ok cool, thanks for looking into it!
