### ISSUE TITLE
As a user i want to be able to “publish” a revision (i.e. link to a specific revision) with a share link

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#835]
i.e. be able to link to a specific version of the notebook e.g. http://extremely-alpha.iodide.io/notebooks/1234?revision=5678

Note this is only about being able to generate permalinks. Being able to flip back/forth between revisions with some kind of UI will be covered elsewhere.

**Comment by hamilton** [comment]
@wlach another approach might be to consider how Github gists are structured. Take [this notebook](https://gist.github.com/hamilton/db97f68edd8109fc82f7a6e45142f9ef) for example. If I go to 

```https://gist.github.com/hamilton/db97f68edd8109fc82f7a6e45142f9ef```

I get the most recent version. However, if I go to 

```https://gist.github.com/hamilton/db97f68edd8109fc82f7a6e45142f9ef/6f5564a5d4e14f62113dd85411527db46dab8bf0```

I get one particular revision. So the pattern could be `<server_url>/<user>/<notebook-id>/<revision_id>`as well.

**Comment by hamilton** [comment]
As of #860, you can now view a particular revision.

**Comment by hamilton** [comment]
@bcolloran ^^^ I recognize this is not a complete feature but we have the link part finished as per @wlach's querystring structure, at least.

**Comment by bcolloran** [comment]
cool! that actually sounds like what we were aiming for wrt to a sharable link. what parts are still missing?

**Comment by hamilton** [comment]
The default saving story for one of your own revisions is to just throw it to the top of the stack of revisions. So that becomes the "latest version" of the notebook, though whatever was previously the latest version is just another revision. We should probably discuss what `meta+s` should explicitly do in this circumstance.

**Comment by bcolloran** [comment]
ah gotcha, but is this specific user story (being able to share a link to a previous revision) complete, even if the story around branching off of a previous revision is not? for the later we have e.g. #868

**Comment by hamilton** [comment]
Yes, the "share a link to previous revision" story is complete. Given the wording of #868, that other story is also complete - if I open a revision and save, I do not lose my previous work, since what was the newest version of that notebook is itself a revision, so I can just go back to that revision listed on `/notebook/<nb-id>/revisions/`. This is probably _not_ the branching-off story we want to support however.

**Comment by bcolloran** [comment]
agreed, and also agreed that this does close #868
