### ISSUE TITLE
Local storage doesn't work on any browser tried

### ISSUE THREAD

**Issue by louisabraham** [iodide-project/iodide#852]
Following what I described in #821, I cannot get local storage saving to work, or more precisely storage loading.

I opened https://iodide.io/iodide-examples/what-a-web-notebook-looks-like.html and wiped the local storage: ![](https://user-images.githubusercontent.com/13174805/44883591-ed001b80-acb7-11e8-8f4e-0da6507bf0b8.png)

Then I modify a cell and hit cmd+S:
![](https://user-images.githubusercontent.com/13174805/44883651-246ec800-acb8-11e8-8523-fabb1b2f863d.png)

Then I refresh the page, my modifications are gone, and the history is empty as well BUT the local storage is there:
![](https://user-images.githubusercontent.com/13174805/44883701-541dd000-acb8-11e8-8d27-d4eaa56146d0.png)

Do you have any idea of what could cause the local storage problem? I reproduced it with Firefox and Chromium. It basically makes the save feature unusable. As you can see in the screenshots above, my local data is not off (or so it seems).

**Comment by wlach** [comment]
@louisabraham the current localstorage-based save system was removed in 1ed77b2dde922dc5abea90b9eb389d5b8e9c70f.  It's just too confusing in its current form, since it wasn't possible to share the notebook that you stored locally.

The approach outlined in #853 is for the server-side component we're working on. But of course other approaches (e.g. editing a notebook on a file system) are still possible. Open to exploring other options for when iodide is used in other contexts as well.

**Comment by louisabraham** [comment]
Oh. It is **very** sad and disappointing. I built the OCaml support precisely in the hope of having a portable notebook with in-browser save.

>  It's just too confusing in its current form, since it wasn't possible to share the notebook that you stored locally.

I do not agree, one could just export the notebook. In the current version, if you inadvertently close or reload the tab, you just lose all your progress.

Would you consider re-enabling local storage again? It would be really useful.

For example, I wanted to use iodide for teachers to put exercise notebooks on their static websites. This way, the student could just work in her browser, from either the website or a downloaded version and quickly save with ctrl+S. Now (if I understand well) there is no static solution that can save without creating a new file.

@bcolloran do you plan to include support for static websites in your implementation of #853?

**Comment by wlach** [comment]
Some kind of basic "autosave the current notebook" implementation might not be crazy (and could cooperate with a server implementation as a last-resort save in case the internet connection is lost), but I don't think we'll bring back the old implementation in its current form. @mdboom had the idea of having client-side plugins that would allow integrating the notebook with arbitrary server-side solutions, which might be something to support in the future.

Is there any reason why you couldn't bring up your own instance of the iodide server, once we've reached a basic level of completeness (should be very soon)? We're running https://extremely-alpha.iodide.io on a heroku hobby instance, which runs at less than $10/mo.

**Comment by louisabraham** [comment]
Plugins sound complicated.

> Is there any reason why you couldn't bring up your own instance of the iodide server, once we've reached a basic level of completeness (should be very soon)?

I intended to propose iodide to OCaml teachers. The target is computer science teachers who just want a very simple setup for students to be able to complete exercises. Maintaining a server is a bit tedious and I would like to make the entry barrier as low as possible (as low as asking students to install OCaml, which puts the effort on them).
On the other hand, most teachers have a **static** personal page hosted by the university. And github.io offers free hosting too.

For this reason, I really hope that a static version of iodide will be maintained.

I just don't understand why you removed a feature that was useful and didn't do any harm. The ctrl-s is not very important (more psychological), but the auto-save is really necessary. I'm sure you have your own reasons, could you explain them?

**Comment by wlach** [comment]
Now that we have a server basically working, our emphasis is going to shift to making sure that saving/loading notebooks works well in that context. For example, the "save" command in the menu is now wired up to save the notebook there (when run as part of the server) and we're working on adding functionality to let people browse collections of notebooks by user (superseding the localstorage based browser). In my experience, trying to maintain a conflicting feature set that is not actively being used or tested doesn't tend to work out very well.

To be clear, we'll still be supporting the static version of iodide -- just not this particular feature as it was implemented before. HOWEVER, if auto-save (restore) is all you need, we can probably bring that back without too much effort. As I mentioned, we were thinking we might want to bring that back as a complement to the new server-based notebook sharing feature.

**Comment by bcolloran** [comment]
@louisabraham thank you filing this issue and clarifying your needs! :-)

Yep, the server will host user notebooks. The idea is to allow anyone anywhere to instantly save and share their notebooks on any machine with a web browser, including on machines where people might not have simple access to the file system (things like school/university computer labs).

We had originally built iodide around the idea of a pure file-based workflow, but our versions and experiments revealed that the workflow was quite unwieldy when saving of notebooks was primarily done in the the browser via localStorage (you can look at #351 for a partial recounting of some of the difficulties we encountered)

As @wlach said, we're focusing on getting this server-based saving workflow working at the moment, because based on our initial experiments, the purely file-based workflow wasn't able to provide the "low friction" experience we think is important for enabling people to drop in and experiment with code, learn from and extend other people's examples, etc. That has meant that in the short term, we've stripped out the local storage functionality as our main saving story. But we will be adding local autosave in as we clarify how those parts should work together. As you said, we don't want people to lose work if they accidentally refresh a page, if they lose their internet connection, etc.

**Comment by louisabraham** [comment]
> Yep, the server will host user notebooks. The idea is to allow anyone anywhere to instantly save and share their notebooks on any machine with a web browser, including on machines where people might not have simple access to the file system (things like school/university computer labs).

I really look forward to it. Maybe you can inspire yourself from https://sketch.sh/.

About #351, I understand it causes some issues, and for example the local files issue is confusing. Thanks a lot for clarifying.

However, local storage is really needed not to lose your modifications by accident (just by closing the tab).

Maybe there should be two different modes: one for static websites and saved html files (assuming they stay at the same place or are exported to new files correctly), and one with server synchronization.

**Comment by hamilton** [comment]
@louisabraham #894 is where we'll be tracking progress on more properly implementing the localStorage autosaving feature. Thank for the issue!
